### ISSUE TITLE
Photos should also save to "Photo Library"

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#100]
Currently photos taken in the app are not accessible in the Photo Library. They only exist in the Strabo-Mobile app. Users should be able to get at those photos with out Strabo.

**Comment by jessica-azgs** [comment]
Save in app and save on device. When downloading spots from db don't save to device, just in app but have option of saving individual pictures to device.

**Comment by ginxwar** [comment]
referencing https://github.com/StraboSpot/strabo-mobile/issues/108
