### ISSUE TITLE
Enter button goes to next field in form

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#101]

**Comment by smrazgs** [comment]
Enter should save information in current field and move to next. Tab just moves to next field. This requires that a tab order is assigned, and ideally can be customized

**Comment by jessica-azgs** [comment]
This doesn't make any sense for a mobile device and would be more effort than it's worth. Either way it would require 1 tap to get to the next field. Tapping a 'Next' button or tapping the next field on the form.
