### ISSUE TITLE
Split forms into tabs

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#104]
3 tabs
- Main (common fields)
- Data
- Relations

**Comment by ginxwar** [comment]
See cb30a07ff167fb179022662480f40960021c5698.  I added a tab container to the spot page.  The only issue remaining is that the tab header doesn't change when the tab is selected/active.

Minor annoyance for now, but the functionality works.

**Comment by jessica-azgs** [comment]
The top of the content is hiding under the tabs. However, I think tabs are supposed to be done so they each have their own state. That's how all the examples are but combining the tabs with the sidemenu is more complex. I haven't been able to get it working yet.

I found the following examples:
- http://codepen.io/anon/pen/azrWKX - But uses an old ionic
- http://codepen.io/gnomeontherun/pen/tbvdH - But has the tabs on every page

These 2 tab-only examples don't have content hiding under the tab bar
- http://codepen.io/mhartington/pen/zxwwGR
- http://codepen.io/mhartington/pen/pvRyeZ

**Comment by jessica-azgs** [comment]
Fixed the functionality for the tabs but it is not separated into states. May not need to do this now.
