### ISSUE TITLE
Labels for orientations

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#111]
Data points associated with orientation measurements:
Would be more useful if labels were of measures dip or plunge (for planar or linear features, respectively). For example. Right now, the label is for the spot name (or ID default if no name entered). Instead, it would be preferable if it could be the dip or plunge of the measurement.

**Comment by jessica-azgs** [comment]
Done in commit 8caa76106086d4f5f916dc7a6a61654419d90e94
