### ISSUE TITLE
Upload and download from db by Dataset

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#120]
Add function to create projects (CRUD operations...) and associate data with a project. Upload and download data to StraboMaster server dB by project.

**Comment by smrazgs** [comment]
For now a spot can only be associated with one project. Can create a spot and upload to different projects, but that creates copies of the spot. Spot gets different identifier in the two projects.

**Comment by jessica-azgs** [comment]
Projects will now be called Datasets instead. Projects will be used in the future as a more all-encompassing term.
