### ISSUE TITLE
More user friendly startup to app

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#121]
We should start the app with a login and then a way to make a new project or use an existing project. Right now the login is buried in the sync function.

**Comment by jessica-azgs** [comment]
You might be starting up the app in an offline environment though so you wouldn't be able to log on right away.

**Comment by jessica-azgs** [comment]
Created a startup login screen which also contains a link to register on from the strabospot website and a skip button in the lower right if you do not want to log in.
