### ISSUE TITLE
rock description for points

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#122]
The current version only uses rock description for polygons. The rock description should be available for all points on the same tab as notes.

**Comment by JEAndrew** [comment]
Could I fix this using kobo forms?

**Comment by zmichels** [comment]
Yes, I think you can.

**Comment by jessica-azgs** [comment]
Do you mean you want the Rock Description option to appear under the first level items for Point as well as for Polygon? Like Contacts, the only thing that can be done in Kobo for this, as it is a top level item, is to change the title so I know Rock Description also goes with Points.

**Comment by JEAndrew** [comment]
I should clarify what first level is, I meant on the data input side once a point was made on the map. We could stick the rock description items (I added a few more items to these kobo forms) on the same tab as the notes.

**Comment by panamint55** [comment]
Are you going to Tucson?

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************
