### ISSUE TITLE
contacts under 1st level points

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#123]
The current version for creating points has a first level option 'contacts'. This leads to a second level for observations of contact type and subtype. This is useless as point data and it is more fully served under the trace (line) type of data. I propose to get rid of contact in first-level points, but keep an option for strike and dip of contact under orientations. One can always spot-link to a contact trace. Is this something I could do in kobo forms?

**Comment by jessica-azgs** [comment]
I need to update this in the app, you can't do the first level items in KoBo, except to change the form title from `Contact: Outcrop (point) or Trace (line)` to `Contact: Trace (line)`, which should be done. What about Fault and Fold? Should these just be under Lines too. This is super simple for me to change. @zmichels Are you both in agreement here? Should I change Contact so it only show up under Lines for the first level items?

**Comment by JEAndrew** [comment]
I am trying to think through how to best organize the point data input choices one a point has been placed on the map. Right now it seems like the best organization would be to have 4 choices for points: planar attitudes, linear attitudes, sample locations, and notes. I am not sure how a spot grouping choice fits in with points on a map. Then under planar attribute point details tab there would be choices of: 
-contact
-intrusion
-bedding
-compositional banding
-foliation (subchoices on details tab of: cleavage; axial planar foliation; compaction foliation; flow foliation; axial planar foliation)
-fault
-shear zone
-shear fracture
-joint
-vein

how does this sound? any thoughts?

**Comment by JEAndrew** [comment]
Should I do the reformat of Kobo forms to the formats described above? I will make backups of the forms before I begin.

**Comment by smrazgs** [comment]
I think the scenario for a point location on a contact is to record a location where the contact is well exposed and can be described, even if there's no orientation measurement at that location.  Could be considered notes. @jessica-azgs @ginxwar -- what would be the best way to have multiple interface form configurations to compare? I'll start a new issue on that.
