### ISSUE TITLE
NOTICE-- backlog document-- please have look

### ISSUE THREAD

**Issue by smrazgs** [StraboSpot/strabo-mobile#124]
I've created a backlog document in the Strabo-documents repository with a start at a project backlog list. Please have a look and add. We'll need to prioritize getting stuff done. Focus in near term is on a working basic system for Zach and Doug to be field testing this summer.
https://github.com/StraboSpot/strabo-documents/blob/master/StraboBacklog.md

**Comment by jessica-azgs** [comment]
Outdated. See #198
