### ISSUE TITLE
Offline Maps: Tile size does not match estimated download size

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#130]
In the Offline Maps list, the file size for the saved tiles does not match (is not even close) to the estimated offline tile size from the Save Offline Map page.

**Comment by ginxwar** [comment]
The file size was just a guess (https://github.com/StraboSpot/strabo-mobile/blob/b58d1c24f1fa932e127d15dade35623d566085f6/www/js/factories/SlippyTileNamesFactory.js#L81) when I committed this.

The hard part about this is that the tile sizes vary immensely, and it ranges depending on macrostrat vs satellite vs street.  You could have macrostrat tiles ranging from 425 bytes to satellite tiles that are 30,000+ bytes.

Would you be ok if I just removed he estimate byte download and we just list only the number of tiles instead?

If we really want a more accurate representation, we could create rolling averages after we download each tile and update the byte estimation as the download progresses.

Let me know if you want me to pursue this or remove the estimate entirely.

**Comment by jessica-azgs** [comment]
@ginxwar Yeah, probably better just to remove the estimate then.

**Comment by ginxwar** [comment]
estimate removed in 200fb1a02faad7060024d011441989ef26df90ff
