### ISSUE TITLE
feature naming

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#131]
Is there a way to set up a default name convention for naming user created features. For example I might want to make all of my points from Kansas to have a label with the prefix KS followed by a number. The number would start at 0 and progress as points are added. Maybe it could be set up on the details tab where if the user changes the name from the default long numeric, the app could be smart enough to use the prefix for subsequent points?

**Comment by jessica-azgs** [comment]
Added Settings menu item with options for a default spot name prefix, root and suffix. If a default root is not entered by the user the app will use a timestamp.
