### ISSUE TITLE
Traces on map can't be seen

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#133]
The traces are still in the spot list but are not visible on the map. Is this related to the map layer list which now only has faults for spot types.

**Comment by JEAndrew** [comment]
Now points are not showing up on the map either. The points and traces still appear in the spot list.

**Comment by ginxwar** [comment]
@JEAndrew could you try again?  I had some symbology images used as placeholders and likely it wasn't showing up properly for some of the points.  I believe I have just fixed them now.

**Comment by JEAndrew** [comment]
None of my points are drawn. I can zoom to the feature but nothing shows up.

**Comment by ginxwar** [comment]
Hmm, are you running the latest version of the app?  If not, I think @jessica-azgs may need to bump the version on the strabo build so you can download the latest and see if this works.

**Comment by JEAndrew** [comment]
i got it to work by uninstalling and then reinstalling.  Is there a way to have the phonegap site say when the app has been undated, or a way to number the updates? (issue #135 )
