### ISSUE TITLE
Workflow and Content Models

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#140]
From @JEAndrew :

The point work flow:

1. user clicks point on the map.
2. brings up menu of attitudes, sample location or spots
3. tabs open: 4 tabs. 1.=details (attitudes form); 2.= General (same); 3. = rock description (kobo form); 4. Spot (same).

I have the attitudes form mostly populated and I am finishing the set up for skip and display of the items. I can upload xls and csv versions of the new kobo attitude form, if that helps.

the traces work flow will be similar.

1. The user draws  aline on map.
2. Menu comes up: A. = trace B.= spot
3. I will make a kobo form called traces that incorporates the forms we already use in one package.

**Comment by jessica-azgs** [comment]
From @JEAndrew :

More thoughts. I talked with others and they recommend new titles to the tabs. Tab #1 = 'Measurements' based on the attitudes kobo form; Tab #2 = 'Notes and Descriptions' with station ID, notes, rock descriptions (kobo form), rock sample (kobo form), photos, but no location data; Tab #3 "Location and Spot links' with the lat-long and spot data.

This changes the workflow a little. The user creates  apoint and then they have a choice of observations (measurements and notes, ect...) or spot data. I am unsure of what the spot point does, so maybe that would disappear.

The work flow for lines on the map would have the options of 'Contact or Trace' or Spot. The #3 tab would be the same but tab #1 would be called 'Observations' and Tab #2 would only have line ID, notes, and photos.

**Comment by jessica-azgs** [comment]
From @JEAndrew :+1: 

'Sample location' will occur on the #2 tab with notes and rock descriptions. Can you call up the kobo forms fro rock description and rock sample for the app or should I combine them in a new kobo form?

For the lines on the map data, we should call it 'Contacts and Traces' instead of just 'Traces'.

polygons will have polygon ID, rock descriptions, notes, photos on a tab and the other tab will be the spot data.

**Comment by jessica-azgs** [comment]
So is this what we have?

Point Drawn on Map
Open form with the following tabs:
1. Measurements (Attitudes KoBo Form)
2. Notes & Descriptions (ID, notes, photos, rock descriptions, rock sample, sample location)
3. Location & Links (location, links and groups)

Line Drawn on Map
Open form with the following tabs:
1. Observations (Observations KoBo Form?)
2. Notes & Descriptions (ID, notes, photos)
3. Location & Links (location, links and groups)
 
Polygon Drawn on Map
Open form with the following tabs:
1. ??
2. Notes & Descriptions (ID, notes, photos, rock descriptions)
3. Location & Links (location, links and groups)

This is ignoring the issue of the Spot Grouping for now (which now can be made from the map when creating a point, line or polygon). Perhaps we can make a special spot grouping button on the map where the user can directly select the spots in a group. If we do this then placing a point, line or polygon on a map can call up the form directly instead of first showing a menu to select from, as it does now.

**Comment by jessica-azgs** [comment]
@JEAndrew It is a lot less work if we can limit the number of different KoBo forms that we will be using. Can Tab 1 for points, lines and polygons use the same form, just show different fields based on skip logic? Can rock descriptions, rock sample and sample location be incorporated into the form used on Tab 1? It's more complicated to split them onto another tab.

**Comment by JEAndrew** [comment]
I think it would be fine to simplify things onto one form. Tabs are not really needed. 

Ignoring the spot items for now, we require only 3 kobo forms: a point kobo, a contacts-traces kobo and polygon kobo? it seems difficult to use the same form for pts, lines, polys, unless the kobo can automatically know whether it is point, line or poly input.

**Comment by jessica-azgs** [comment]
We can still use the tabs but it would be easiest if only one of the tabs had a form based off KoBo forms. The Notes Tab (Tab 2) can still have ID, Notes & Photos (those can be hardcoded), unless you want ID as part of the KoBo form on Tab 1. I would guess that the Notes field can get long depending how wordy people are with their notes so may be better to keep that in Tab 2. And definitely best to have the links and groups in Tab 3, but those don't use a KoBo form either, so that's fine.

If you are going to end up repeating a lot of the same fields between the point, line and polygon forms then, yes, it might be best to make them 1 form and then let skip logic handle which fields appear. You would need to make the very first field a drop down with the selection options of point, line and polygon so you could base skip logic off of that. I can hide that from the user in the app though and determine whether it is a point, line or polygon from what they draw on the map and then apply the skip logic.

**Comment by jessica-azgs** [comment]
In Kobo I see 
points: Measurements & Observations form
lines: Contacts & Traces form

but what about polygons?  If the form for polygons is not ready, even just having a dummy form with very few fields for now would be good.

@JEAndrew As you are editing the forms makes sure you check the data column name (under the settings gear for each field) and the defined vocabulary field values (on the right in grey next to each vocabulary term) to make sure they are in lowercase and make sense and edit if not. Sometimes Kobo's auto field name creation doesn't give as friendly of a name as we may want.

**Comment by JEAndrew** [comment]
@jessica-azgs The polygons will be the 'Rock Description' form. The point form is ready and I am cleaning up the line form right now, hopefully it will be done this afternoon.

**Comment by jessica-azgs** [comment]
Oh. I thought Rock Descriptions was under Measurements & Observations?

One thing to note now is that the Measurements & Observations form takes longer to load now because there are so many fields and complex skip logic. It's not terrible but waiting the extra 2 seconds is a slight annoyance to the user.

**Comment by JEAndrew** [comment]
Rock descriptions is included as a point observation in 'Measurements and Observations'. A separate Rock descriptions is the only item for polygons. I am finished with versions for the point, line and polygon kobos (M&O, C&T, and RockDesc).

**Comment by jessica-azgs** [comment]
The Rock Description form I want is the one that is labeled as Rock Description: Outcrop(point) or Trace(line) or Area(polygon)? If so it should just be labeled as Rock Description (polygon). And, for further clarity, @JEAndrew can you remove the forms we're not using now? We have backups from 4-27 in https://github.com/StraboSpot/strabo-documents/tree/master/KoBo%20Forms.

**Comment by JEAndrew** [comment]
We will have to experiment with the point kobo to make it faster. The fall-back solution is move the 'Rock Descriptions' and 'Rock Sample' parts to separate kobo forms to be separate choices from the observations form when the user creates a point. You have these currently set up that way. Do you think taking off the 39 lines of rock samples and description questions on the M&O kobo file would speed things up significantly? The rock sample and rock description kobo already exist, so I could just delete them from 'Measurements & Observations'.

**Comment by panamint55** [comment]
Do we need a call today or would tomorrow be better?

Doug

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessica-azgs** [comment]
@JEAndrew Check out the way I've reorganized the tabs and see if we can build off of that now. I haven't actually moved Rock Descriptions over to the new tab but will do when I am in the office next, which will be next Tuesday. I tested it and it didn't speed up things too much but I have a few other ideas to try.

**Comment by JEAndrew** [comment]
@jessica-azgs The tabs are a good approach, but on a phone they seem too many. We could consolidate items on the tabs. Maybe combine notes + rock descriptions + photos on one tab...

**Comment by jessica-azgs** [comment]
@JEAndrew If you drag the tab bar to the left you can access all of the tabs on a phone. I'd like to leave Rock Descriptions in its own tab because of its complexity. The Rock Descriptions tab is not loading as fast as I would like on its own so we shouldn't combine it with anything else. Combining Notes & Photos is easy but we need to find the right balance between having too much on each tab and too many tabs. Since the app should primarily be used on a tablet and all of the current tabs are visible on a tablet (and still accessible on a smaller screen) I think it is cleaner to have each tab be pretty specific so the information is easier to find and there is less scrolling through one tab with a lot of content.

Tabs we have:

1. **Detail**: Measurements & Observations (points), Contacts & Traces (lines), and **What here??** (polygons)
1. **Notes**: Name, Date & Notes 
1. **Photos**: Thumbnails of photos
1. **Georeference**: Geometry & Location
1. **Links**: List of links to other Spots
1. **Groups**: List of groups of which this Spot is a member
1. **Group Members**: List of members in the Spot *(this tab is only visible when the Spot is a Spot Group)*
1. **Rock Description**
1. **Rock Sample**

What I still need from you, or someone, are:

- Final drafts for the forms for tab 1 above. This includes what you want on the Detail tab if someone draws a polygon since Rock Descriptions is now it's own tab.
- Final draft for the Rock Description form (which I know is already in KoBo but would like to confirm that that doesn't just apply when the Spot is a polygon, like it states in parentheses)
- The Rock Sample form (unless you don't want a Rock Sample tab)

**Comment by JEAndrew** [comment]
I think this app may have a lot more use on phones. Nearly everyone has one, whereas GPS tablets are less common. So we need to think of small screen real estate.

We should lump some of the tab content:  
-combine spot links, groups and group members.

Other than the spot data being grouped, I think the tab layout above could work. We may choose to shorten the longer names to save screen space. Georeference to geo (or any other suggestions?'). The details tab could be changed to Obs (short for observations?, anyone else have suggestions?).

**Comment by JEAndrew** [comment]
The primary focus of the polygon file is rock description, so maybe the Observation (=details) and rock-sample tabs would not be activated?

**Comment by JEAndrew** [comment]
I will update the measurements kobo today to take out the rock sample and rock description portions. I can update the name of the rock description kobo to take into account it's applicability to points (and possibly to contacts?).

**Comment by jessica-azgs** [comment]
@JEAndrew I don't see Rock Sample in KoBo. I do see Sample Locality (which says only applies to points). Is that supposed to be Rock Sample?

**Comment by JEAndrew** [comment]
Yes, sample locality.

**Comment by jessica-azgs** [comment]
@JEAndrew So you do want it called Sample Locality instead of Rock Sample? And does it only apply to points? If not, you could change the title in KoBo so I make sure I have what you want?

**Comment by JEAndrew** [comment]
I'll update the name in kobo and yes it applies only to points.
