### ISSUE TITLE
Save current spot when switching between tabs

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#142]
Temporarily save spot values in `CurrentSpot` service when when switching between tabs in a spot. Already done for Details, Notes and Rock Description tabs. Use `$scope.switchTabs` method. Currently geometry, links, groups, and group members are not written to the spot until the Save button is clicked (and code enters `$scope.submit`). Need to write these to the spot when tab is switch or when the save button is clicked. However, the spot should not be written to local storage until save button is pressed. That means if you navigate off of the pages for a particular spot `CurrentSpot` is cleared out (currently done in spots.js and map.js with `CurrentSpot.clearCurrentSpot();`).

**Comment by JEAndrew** [comment]
Good idea!
