### ISSUE TITLE
MULTIPOLYGON Feature Type Not Supported in Mobile App

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#145]
I have loaded several shape files containing MULTIPOLYGON type features, and the mobile app doesn't seem to support them. This feature type is very common in shapefiles and should be supported.

**Comment by jessica-azgs** [comment]
Added support for MultiPoint, MultiLineString, and MulitPoloygon geojson features with commit 47d97e6bd61492558c0e296b653d328cf19ef660. These types of features can be viewed on the map and properties for the features can be viewed but you cannot edit the location/geometry of these features from the app. This could be later addition if we need it. And for clarity, under `properties.type` we have `point` for MulitPoint, `line` for MulitLineString and `polygon` or `group` for MulitPolygon. @jasonash Could you test it out with the features you have and close this issue if it seems to be working for you as well?

**Comment by jasonash** [comment]
@jessica-azgs MULTI-features are displaying correctly now. I am able to click-identify them fine now.

**Comment by jessica-azgs** [comment]
Ok, closing this then.
