### ISSUE TITLE
order of question answers as appear in app

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#146]
The app takes the question answers choices in kobo and changes the order to alphabetical. Can we keep the kobo order to these answers.

**Comment by jessica-azgs** [comment]
Ok, this was an easy fix @JEAndrew so I quickly implemented it (ca8cfc6e9b0a275c1f721df63eb68669ea4c507c) before going back through the emails from last week containing the bigger issues. None of the answers for selects ones (dropdowns) or select multiples (checkboxes) will be alphabetized anymore but will be however you have them in KoBo. I have not pulled in the most recent KoBo forms yet or pulled this change into the app version that you are looking at. Will do sometime today and let you know.
