### ISSUE TITLE
Rock descriptions in app

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#147]
The rock descriptions in the app would be better as a way to define new units and then reference an already unit and maybe add a note to that description. Geologists use a unit label that represents the rock description, rock type, age and other data. In the app we could have user choose from an existing unit description or an option to create a new one?

**Comment by JEAndrew** [comment]
I am thinking of workinhg this using two different kobo forms to speed things up. One would define a new unit and the other would let the user choose from a list of already units already defined by the user. As an advance option, these unit definitions could be shareable to other users. How do we do this? I can do all of the form work.

**Comment by jessica-azgs** [comment]
Done.
