### ISSUE TITLE
symbol rotating by wrong field

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#149]
The symbol that appears on the map after I enter a planar feature seems to be rotated by the dip value rather than the strike/azimuth value. The symbol should rotate based on value entered for "Strike".
Same goes for any symbols we use for lines... they should be rotated by the "trend" value, not the "plunge" value.

**Comment by jessica-azgs** [comment]
Fixed with latest commit ded3dcab6eab14ee8ff81da25e5c2f0bcea6d2d1. Thought that was working before so not sure when it changed. @ginxwar
