### ISSUE TITLE
Upload/Download photos when syncing spots

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#150]
Jason has written the API but this needs to be implemented in the app. While looking at this also look at whether the images element should be a child of properties in the geojson as opposed to a sibling of properties, like it is now.

**Comment by jessica-azgs** [comment]
Did some work with this in the branch https://github.com/StraboSpot/strabo-mobile/tree/imageUpload but still not working.

**Comment by ginxwar** [comment]
Fixed in 864333c6fe5262ca22a708a7099f87ab4b017f54.  I like the idea of "images" as a sibling to "properties".  If it were a child of "properties", I feel that it would get too crowded.

**Comment by jessica-azgs** [comment]
@ginxwar Can you see if you can get the download working too? I added code for it in the branch but not sure about the format we need to actually save the image in the spot locally.

**Comment by ginxwar** [comment]
Corrected image download in c457b04788231b6e7b6a22a1aa0d1363fc94a007.  Problem was due to XHR coming back as a string and not as a blob.  Then needed to convert blob back to base64 encoded string.

**Comment by jessica-azgs** [comment]
@ginxwar Great, this is looking good and I merged it in with master. Still have a problem with the server overwriting images since they all have the same filename but Jason says he'll fix it sever-side tomorrow. See https://github.com/StraboSpot/strabo-server/issues/11
