### ISSUE TITLE
Ignore validation routine if form untouched

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#153]
Details tab should ALWAYS be validated when switching tabs or saving a spot. However, switching tabs or saving from the Rock Description tab or Rock Sample tab should not run the validation routine if none of their form fields have even been touched. However, if we have `spot.properties.type == 'polygon'` (Rock Description Only Spot) then the validation routine should ALWAYS run for Rock Description. This was implemented by passing `$pristine` to `switchTabs` [L18](https://github.com/StraboSpot/strabo-mobile/blob/088d2cf523cb0f5c12ec6debde9e8a4e28515f7c/www/templates/tabs/rockdescription.html#L18) but this needs to be implemented in a different way now given the spot controller refactor.

**Comment by ginxwar** [comment]
Fixed in b847346d3db79b776e9dd223ac2130f23f2474ec
