### ISSUE TITLE
background processing of image upload

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#156]
Uploading images takes awhile so we should look into how we can have this run in the background so the user can still use the app. And/Or we should also show some sort of better progress for image uploads to the user since it does take awhile.

**Comment by jessica-azgs** [comment]
Uploading pics is super fast on iOS compared to Android (Galaxy S6).

**Comment by jessicagood** [comment]
Uploading is fast enough now with the new server that I don't think this is a problem and the user can wait.
