### ISSUE TITLE
Adding photos from gallery making duplicates

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#158]
On iPad (can't test on Android since photos is crashing at the moment) selecting a photo from the device gallery is creating a duplicate photo on the device under today's date in the iOS Photos gallery.

**Comment by ginxwar** [comment]
Fixed in 1f66bbca1175167317b44f89b0a4a56221d91e14

**Comment by jessica-azgs** [comment]
Looks to be working.
