### ISSUE TITLE
Android camera is broken

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#160]
When using the camera function in Android, after taking a picture, the system was throwing a "Unfortunately, Photos has stopped" error.

**Comment by ginxwar** [comment]
Fixed in 4bf0376d95121c9c48c384a18a3f35d51db4874b, 29f9a4b6878448bf3c1318ba55987b611fdde014.
This issue was difficult to investigate due to a number of variables:

* Google updated the Photos app
* On my Nexus4, I updated from 5.1 to Android 5.1.1
* Strabo was updated to Cordova 5

Eventually, after lots of trial and error, I pinpointed the error to the camera encoding type for the image and changed it from PNG to JPEG.  The camera was able to do PNG encoding because it had worked in previous builds but obviously something had changed that no longer allows this.

I tested both my ipad mini and android devices and both devices can now take pictures from the camera again.

**Comment by JEAndrew** [comment]
App crashes after every other photo added in Strabo via camera capture. (using up to date Samsung Galaxy S5)

**Comment by ginxwar** [comment]
@JEAndrew are you getting an error message when it crashes?  Or does it just abruptly stop for no reason?

**Comment by JEAndrew** [comment]
I just used the photo part of the app and the app crashed with no message

**Comment by jessica-azgs** [comment]
Which version of the app are you using @JEAndrew? It is working fine for me on my Galaxy S6 using version 0.6.4 and adding multiple pictures from the camera and from the photo library. It's hard to debug when I can't recreate the problem so whatever other information you could give me about exact steps may help.
