### ISSUE TITLE
HTTP Basic Authorization case sensitivity

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#161]
We should always force the username/email of the login to lowercase before passing to the strabo-server api for authentication.  My phone *always* tries to uppercase my name in my email box and in doing so changes the base64 encoding in the HTTP Authorization header, causing my authentication to fail.

**Comment by ginxwar** [comment]
fixed in edaef2f60ecfcfab5c5962ea0bd8803120efce64

**Comment by jasonash** [comment]
@ginxwar I have altered the server-side code to also force email/username to lowercase on signup and login. This will prevent users from signing up for an account using a mixed-case email address. There was only one such mixed-case email already in existence, but I have fixed it in the db.

**Comment by jessica-azgs** [comment]
Great! I know others were having problems with this too, we just never addressed it.

**Comment by jessica-azgs** [comment]
This fix was incomplete. Only worked on initial authentication not on subsequent server interactions. Fixed with commit 653e5d3119b3d226f2da2d21a475007db62d18ff.
