### ISSUE TITLE
Lineation symbols not working / displaying

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#162]
The lineation symbol doesn't seem to be working any more. It was working with this same data before, but I did update the app. Now I just get dots whenever I load the data and no arrows. I have internet tonight before gong to camp with little to no cell service tomorrow for a few days.
Any ideas what I can maybe do/change to get the symbols back?

**Comment by zmichels** [comment]
when i enter a lineation from the app, the symbol works. But the downloaded data from StraboSpot is not. I'm confused because it worked before wit these same uploaded shapefiles. But becuse the ones entered in the app is good, I am thinking the problem is either with my shapefiles or with the upload process. I haven't changed them from before, but I can edit them to work if I know how I shoud change them. I have an attribute field that I am assigning to "Lineation Type" during the upload. The field is populated with ' solid_state '
Any thoughts?

**Comment by jessica-azgs** [comment]
@jasonash The app is looking at the linear_feature_type field to determine how to symbolize the spots. Is this still what the upload process allows the user to map something like "Lineation Type" to? If so, @zmichels do your field values of ' solid_state ' really have a leading and trailing space? The value should be 'solid_state' (without the quotes). If that's the case, @jasonash can you strip leading and trailing spaces on upload?

**Comment by jasonash** [comment]
@jessica-azgs linear_feature_type was not an offered field on upload, but I have added it to the upload page under "Linear Feature Type"
@zmichels Can you try your upload again and choose "Linear Feature Type" for the field containing "solid_state"?

**Comment by jessica-azgs** [comment]
@jasonash Great!
