### ISSUE TITLE
ol3 v3.6 or v3.7 will break offline tiles

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#166]
See https://github.com/openlayers/ol3/releases/tag/v3.7.0

**Comment by ginxwar** [comment]
Actually, v3.6 broke offline tiles.  I can confirm that offline tiles does work in v3.5, but not in v3.6

**Comment by ginxwar** [comment]
v3.6 broke the offline tiles and v3.7 *fixes* them.  How nice of the OL3 team. :+1: 

Fixed in bf29d4aa048aaa2219429e86416908a65073f7c9

**Comment by jessica-azgs** [comment]
Yeah, thanks OL3 for breaking it in the first place. Ayy. Thanks for fixing @ginxwar
