### ISSUE TITLE
PhoneGap Build not building for Windows Phone anymore

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#168]
Why is this? Think it changed when cordova was changed to 5.1.1 (https://github.com/StraboSpot/strabo-mobile/issues/159). Doubt anyone is using Windows Phone but should look into this at some point.

**Comment by ginxwar** [comment]
Oh, I changed this because I didn't want to see windows phone on the build.  It was distracting to me. :)  But we could put it back....  this is done in the config.xml file.

**Comment by jessicagood** [comment]
added back in
