### ISSUE TITLE
Sync option not working right

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#172]
The sync option to "Remove all Spots from Dataset and delete Dataset"
Is not removing spots from the device (at least on iOS). It *does* delete the dataset on StraboSpot, but I'm trying to get it off my device.

**Comment by zmichels** [comment]
Same version (0.5.3) on two different iOS devices... 
In both cases the APP shows up in iTunes File Sharing. But the data folders are only present in one of the devices. I have exported the data in the app on BOTH devices. Any idea what's different? I would do a clean install on the not working one, but I would lose all the data I am trying to keep (and my sync isn't working to back it up... Gets stuck on first spot uploading... On all the devices I have tried), so I am trying not to do that. If that's what I need to do tho, let me know and I will just bite the bullet and do it.

**Comment by jessica-azgs** [comment]
Not applicable with new sync functionality.
