### ISSUE TITLE
Download inner zooms from any level?

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#177]
I want to be able to download inner zooms of map tiles regardless of the zoom level I am at. My area is large and downloading all the inner zooms I want requires panning around approximately 12 different screens and saving separately to cover the area. This is tedious and leads to me missing parts. Can we make it so that I can download inner zooms from all levels? If we are worried about people eating too much memory on their devices... Maybe we could add an alert if zoomed out to certain level... But would be great to remove the current limitation.

**Comment by zmichels** [comment]
To be able to do this from Zoom level 12 would make my life much easier... 13 would be ok, too

**Comment by ginxwar** [comment]
I changed the minimum from 15 to 12 in 5534da2178b5391a0c5afa39d93935d365488543.  This is **a lot** of tiles so I'm not sure if it'll crash so please test away.

**Comment by zmichels** [comment]
How can I install this version you refer to?

**Comment by ginxwar** [comment]
Jessica would need to initiate a code pull and rebuild on the phonegap site

**Comment by zmichels** [comment]
Ok. Thanks for info. I'll wait until I get back from the field again to update. I have enough map tiles for now.

Cheers,
Z
