### ISSUE TITLE
Symbol label placement

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#180]
From @JEAndrew:  Is there a way to change the placement of the dip and plunge number? The dip value should be at a position 90 degrees from its current location, placed in the location outward from the hatch mark on the planar symbol. The plunge value needs to be placed a little bit farther out because right now it overlaps the arrow on the linear symbol. (Originally in issue https://github.com/StraboSpot/strabo-mobile/issues/91)

**Comment by ginxwar** [comment]
Just so I understand, do you want something like this?  I want to make sure that the rotation is correct and that you want the text to align next to the sigil box (in this fault surface example)
![drawing](https://cloud.githubusercontent.com/assets/1930629/8924326/33c3b46e-34b1-11e5-9a8d-49570c4a9f8a.png)

**Comment by JEAndrew** [comment]
Perfect.

**Comment by ginxwar** [comment]
Done in e3d963025d1e9087de86519cc2139e4dd869a2d4.  The label also is now rotational aware and rotates along with the image.
