### ISSUE TITLE
Handle field groups in auto-fields directive

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#182]
Some forms created in KoBo Toolbox use field grouping (eg. Preferences). These need to be handled by the auto-fields directive. Currently these are removed from the csv manually before being read by the app.

**Comment by panamint55** [comment]
I am unsure what field grouping is.

Doug

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessica-azgs** [comment]
In the Preferences KoBo form there are two groups that someone entered to organize the fields, Tab Control and Other Preferences. The code I have isn't set up to understand field groups like that so I will need to write additional code to process them. Right now I'm just ignoring groups. (Groups weren't used in the previous set of forms from the spring/summer.)

**Comment by jessica-azgs** [comment]
Implemented with commit ede1443dcbce5f3518a02f37a71ab6d445b70b01
