### ISSUE TITLE
Upgrade to Ionic 1.2

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#185]
Ionic 1.2 released today. Many improvements but I also see breaking changes after just a quick glance at the blog post. See http://blog.ionic.io/announcing-ionic-1-2/

**Comment by panamint55** [comment]
Things are working better with 7.3.  Keep me updated as you can.

Doug

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessica-azgs** [comment]
@JEAndrew In the link above about 1.2 it says 1.2 should give 'significant performance and user experience improvement to your Ionic apps, especially on Android.' Hopefully that will fix the performance issues you're seeing with Android. I'm not upgrading yet though because the upgrade will break a lot of other things so I'll need to devote a good block of time to that.

**Comment by jessica-azgs** [comment]
Updated with commit d17cc1eea3c11e4f148aa4d2da5a8f7419541f37. Only thing I found that needed fixing was removing all `<label>` tabs since they are no longer support. Some related css also needed to be fixed, particularly for select elements.
