### ISSUE TITLE
Add Progress Bar back in

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#186]
I hid the progress bar on the archive tiles page as it was not working correctly. The progress bar was finished way before the tile downloads were actually complete. Need to fix this and should use $http request instead of XMLHttpRequest.

**Comment by panamint55** [comment]
I went to the map quest website and higher resolution shows.  Do we have a problem with something in strabo?

Doug

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessica-azgs** [comment]
Done in commit d686604.
