### ISSUE TITLE
Pixelate map tiles

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#187]
Pixelate map tiles from other zoom level when we don't actually have a tile for a section of map at a specific zoom level.

**Comment by jessica-azgs** [comment]
Might need to automatically download small scale tiles for the world. Now if zoom levels 14-16 downloaded, for example, user just gets a message that there are no tiles if zooms out to zoom level 13 or smaller scale. Would be more help to have the pixelated tiles. Likewise when zooming in.

**Comment by jessicagood** [comment]
Fixed with commit 934731e04ecee530c42721202da83d527657e4e5.
App checks up to five levels of outer zooms to see if there are any tiles that can be stretched to make the map at the requested zoom level. The stretched map tile is drawn on the fly - it's too many tiles to save the images for the stretched tiles. If a tile can't be displayed, just display a white screen instead of showing tile unavailable (this is more similar to how other map providers handle missing tiles).
