### ISSUE TITLE
MapQuest Satellite Tiles Issue

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#188]
The version of MapQuest that we're using through OpenLayers is missing satellite data around Baker, CA (one of the study areas) at high zoom levels. MapQuest.com seems to have this data so why it is also not in the MapQuest tiles we're getting though OpenLayers, I don't know. See the Baker, CA area in the OpenLayers MapQuest example (http://openlayers.org/en/v3.12.0/examples/mapquest.html) to note that these missing tiles is not a problem with Strabo.

BingAerial seems to have much better satellite data for this area so maybe we should integrate this map provider? See OpenLayer example (http://openlayers.org/en/v3.12.0/examples/bing-maps.html). This could take several days though, if we also want to be able to download the tiles, since they are downloaded differently than the other map providers.

@panamint55 Should this be moved up on the priority list?

**Comment by panamint55** [comment]
I think it should go a bit higher once the other functionality is inplace.  A more pixelated very would be fine for now.

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessica-azgs** [comment]
Used Mapbox to overcome this issue.
