### ISSUE TITLE
Daily Setup Page

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#189]
What do we want in the daily setup page? Right now the KoBo form is blank. @panamint55 suggests "free text with stuff for the day. Probably starting gps. Start of tracking for day if we use the. [sic] This is the daily setup tab."

Anyone able to expand the KoBo form for this page?

**Comment by jessicagood** [comment]
Image for the daily log

**Comment by panamint55** [comment]
This does not need to be anything involved.  If they have a lot to put in they will have to add a spot and go that route.
