### ISSUE TITLE
5 levels of data

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#195]
I was able to create the 5 levels with the photo image basemaps. But to view them later in spot mode it is impossible to click through the levels. In spot mode clicking on a spot in the image on image tab just brings you back to the last spot tab, not the next level down spot on the image. This clicking down through the levels works for only one more level when viewing under image basemaps.

**Comment by jessica-azgs** [comment]
@JEAndrew I noticed this yesterday too. Working on a fix.

Navigating through the levels will be easier when the Nest tab is functional and when we have a filter capability on the list of Spots.

**Comment by jessica-azgs** [comment]
Fixed with commit cc43e66
