### ISSUE TITLE
Inferences Tab Form

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#200]
@JEAndrew @zmichels I'm a little confused with the start of the inferences tab. The `Notes for programming on the individual sheets.doc` says the user should chose between “Rosetta” or “Related to Rosetta” outcrop but the KoBo form only gives one option of just choosing Rosetta Outcrop. Could you take a look at KoBo and see if you have it as you want it?

This tab is a little more confusing as it references other data and cannot simply be an export of the KoBo form. The way you wrote it in KoBo is good though, where, for example, you said in the Question Hint, `This needs an autopoulated list of spots to appear like magic here` makes it lot easier to understand.

**Comment by JEAndrew** [comment]
I felt like "related to Rosetta" was unnecessary and could be included in just Rosetta.

**Comment by jessica-azgs** [comment]
Some ideas for this tab:

- be able to make relationships with orientation observations on parent or children spots
- don't have relationship under the Rosetta toggle
- temporal ordering
- relationships between more than 2 orientation observations at a time

**Comment by jessicagood** [comment]
Note from Idaho fieldtrip: Have a field for the confidence when defining a relationship.

**Comment by jessicagood** [comment]
added confidence level with commit b7a03d6d938afeeb126d92250265ee4e06703885
