### ISSUE TITLE
Other Features Tab Clarification

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#201]
@zmichels @JEAndrew Despite looking at the KoBo form, Current sheet, Spreadsheet and Programming Notes for Other Features I'm still confused by what we need here. You say it adds a single new features but there are multiple text fields for features. Or are these fields for descriptions of a feature? Though if so, wouldn't we need a text box for entering the name of the new feature?

**Comment by JEAndrew** [comment]
I was under the impression that these were an outline of future capability when different geoscience disciplines get their database needs set. For now they are notes fields to fill with data in these subject areas.

**Comment by jessica-azgs** [comment]
Ok, I have a pretty flexible format in place now. Does anyone have comments on how this looks?

**Comment by zmichels** [comment]
Looks good to me. 
I realize it is perhaps mostly a template at the moment... However no way to 'save' the information entered yet.
Also... In the available drop down list for Feature Type, we include 'other'. This is great. What I am wondering is if we want a way to further clarify when user selects 'other'... Or if the notes and description are sufficient. I am uncertain at the moment which I would prefer.

**Comment by zmichels** [comment]
NM: I see now how to save by clicking the check mark.
Looks good.
