### ISSUE TITLE
Strabo Other Features

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#203]
When I go to the "other features" tab and add an "other" the new name does not show up in the list - strabo 9.5 on firefox from the website.  I thought these new items populated the list, and I thought I saw this on older versions.  They should go into the list I believe.

**Comment by jessica-azgs** [comment]
If you hit the checkmark at the top instead, of just closing the popup, any feature you add, including any 'other' features, shows up in the list on the Other Features tab.

**Comment by panamint55** [comment]
I tried that.  I will try it again later today or tomorrow.

Doug

**Comment by panamint55** [comment]
When I add an "other feature" it does add it to the spot with type "other" under the list.  But the newly defined "other feature" does not appear in any list when I go to another spot and hit "other feature."  
What I did was go to a spot and add two other features - Test 1 and Test 2 were the names and descriptions.  These were feature type "other.".  I went to a second spot and hit "other feature" with type "other."  But the ones previously defined were not in the list.  I thought this was supposed to add to the list as the other "other" entries should do

**Comment by jessica-azgs** [comment]
Yes, it only adds a new feature within that spot. There was another issue (https://github.com/StraboSpot/strabo-mobile/issues/201) where I talked about not really understanding what was supposed to be on this tab. 

From what you said just now it sounds like you want it to be similar to how Rock Unit works? Where you have some master list of other features tied to a project which you can add to or reference from any spot?

**Comment by panamint55** [comment]
That is correct.

**Comment by jessica-azgs** [comment]
Changed in commit 90c24bb161c05717d16e42c7863b9d558c26ffb7.
See if what we have starting with version 0.9.6 looks better.
