### ISSUE TITLE
Offline Maps

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#205]
I have 18 offline maps with 16314 tiles and 171MB of storage.  When I click on "offline maps" in the menu bar the list appears.  If I quickly scroll to the bottom I can see the Total Number of Tiles and Total Size.  Initially the total size is "0" and the screen locks until it computes and populates the total size.  This can take a while and the screen appears locked the whole time.  

For some reason, it appears that things lock until that field is populated.  The bottom of this image shows the readout when the screen is locked.  One the size appears all is good.
![img_0008](https://cloud.githubusercontent.com/assets/9283127/13380803/7433cfbc-de10-11e5-9c6f-263ad47c62e4.PNG)

**Comment by jessica-azgs** [comment]
This is fixed now. Total Size is no longer calculated since it was taking too long.
