### ISSUE TITLE
tools menu

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#206]
If I go to the "Tools" menu item but then just want to go back to the menu it throws and error.  

Here is what I did.
1) menu
2) select tools
3) pressed menu icon again, and got the following message.

![img_0009](https://cloud.githubusercontent.com/assets/9283127/13380871/8ec06582-de12-11e5-9113-5166fbd8a7d1.PNG)

**Comment by jessica-azgs** [comment]
Yeah I noticed it does that too - which is the correct operation since
those fields are required. It just doesn't make sense for this page yet
since it's not functional. I can make those two fields not required so it
doesn't give the error message.

**Comment by jessica-azgs** [comment]
Made these fields not required in commit f62b6c5576eee654cf6d20bdd415ff7ab1c5c3c9
