### ISSUE TITLE
Delete spots dialog

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#208]
On the sync actions from the spot menu I get the dialog below.  The "remove all spots" dialog message is not complete.  This is a pretty important one, so this should show up to make sure everyone knows what this does.
![img_0012](https://cloud.githubusercontent.com/assets/9283127/13440189/742df3ce-dfb6-11e5-9750-2e8af8e9454f.PNG)

**Comment by panamint55** [comment]
I am also not sure if we want the final option here.  That seems like a data management issue better left for the strabospot website.

**Comment by panamint55** [comment]
We may want to have an explanation for upload describing exactly what it does.

**Comment by jessica-azgs** [comment]
Redoing the whole sync process is next on my to-do list (once I clean up a few other things first) so all of this will change.

**Comment by panamint55** [comment]
Great.

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

From: Jessica Good
Reply-To: StraboSpot/strabo-mobile
Date: Tuesday, March 1, 2016 at 2:09 PM
To: StraboSpot/strabo-mobile
Cc: Doug Walker
Subject: Re: [strabo-mobile] Delete spots dialog (#208)


Redoing the whole sync process is next on my to-do list (once I clean up a few other things first) so all of this will change.

**Comment by jessica-azgs** [comment]
Not applicable anymore with new sync functionality.
