### ISSUE TITLE
Planar Feature Type Other > Wrong skip logic?

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#210]
When setting planar feature type to "other", a new form item of "Other Geological Structures" appears, but this is another controlled list. There doesn't appear to be any way to enter a custom planar feature type.

Alternatively, when setting linear feature type to "other", a new form item "Other Linear Feature" appears. This is a free text field which allows entry of a custom value. This appears to be the correct behavior.

I checked the Kobo forms, and the app is correctly emulating the supplied skip logic. Do the Kobo forms need fixed?

**Comment by jessica-azgs** [comment]
Yes, the KoBo forms would need to be changed then. @JEAndrew @zmichels is the Planar Orientation form working like you want in terms of the 'Other Linear Feature' field that @jasonash mentioned? If it needs to be changed I'm not sure where you'd want 'Other Geological Structures' moved to. Could one of you fix the KoBo form and let me know when I can pull the updated fields into the app? Or let us know if it is functioning correctly now. Thanks!

**Comment by JEAndrew** [comment]
OK, I made a change to KOBO. I added a new text field of 'Other Planar Feature Type' and deleted the 'Other Geological Feature Type' (I moved the 3 options to the 'Planar Feature Type' menu. If the new kobo name messes thigns up I can change it to read 'Other Geological Feature Type'.

**Comment by jessica-azgs** [comment]
Ok, updated that in the app v0.9.10. Thanks @JEAndrew!

**Comment by jasonash** [comment]
It looks like the field names in Planar don't match with Linear now.

Can we change "Other Planar Feature Type" to "Other Planar Feature" and "other_planar_feature_type" to "other_feature"?
It would help to keep the orientation fields aligned if possible.

**Comment by jessica-azgs** [comment]
Of course. I changed it in KoBo forms and in the app. Still v 0.9.10

**Comment by jasonash** [comment]
Awesome! Thanks!
