### ISSUE TITLE
Option to delete all spots

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#211]
There used to be an option to delete all spots from the app when clicking on a small triangle in the upper-right portion of the spots page. This option appears to be missing from 0.9.9.

There is an icon in the upper right menu of the spots page (three small dots) but clicking on it doesn't do anything (on the spots page).

**Comment by jessica-azgs** [comment]
Yeah, I had forgotten to upload the html for the popover when you click on the 3 dots. I fixed that yesterday but never actually incremented the app version number. If you download the latest (though still 0.9.9) it's fixed.

**Comment by jasonash** [comment]
Great! Thanks!
