### ISSUE TITLE
Missing Rock Unit data in strabo app.

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#213]
Missing Rock Unit data in strabo app. It used to be there. It is in the KML and XLS outputs from the database. Everything else seems to be intact.

**Comment by jessica-azgs** [comment]
Are you trying to sync Rock Units from the sever or are new Rock Units entered in the app not showing up? Rock Units don't sync yet, nor do any other project properties. That is part of the sync functionality I'm working on.

**Comment by JEAndrew** [comment]
Yes, from the server, so this now makes sense. Thanks.
