### ISSUE TITLE
modified_timestamp reported incorrectly for Project by Strabo app

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#215]
@jessica-azgs  The Strabo app is reporting "modified_timestamp" as a date/time string, but it should be reported as a unix time stamp (integer).

**Comment by jessica-azgs** [comment]
Ah, yeah, I was just doing `new Date()`. Sounds like it should be `Date.now()`. However do we want the fields `date` and `modified_timestamp` to be represented the same way? Should they both be `Date.now()?` I see in your API description one is a string and the other a number.

**Comment by jasonash** [comment]
It doesn't make any difference to me whether the "date" property is a unix timestamp. I would like to keep "modified_timestamp" a unix timestamp so we can use it later for the sync functionality.

**Comment by jessica-azgs** [comment]
Ok. I just kept `date` as a string but am using the numeric timestamp for `modified_timestamp`. Is Date.now() the same as your unix timestamp?

**Comment by jasonash** [comment]
Unix time is seconds since epoch, UTC, so it should be a ten digit integer, something like 1458754029.

**Comment by jessica-azgs** [comment]
Date.now() Returns the numeric value corresponding to the current time - the number of milliseconds elapsed since 1 January 1970 00:00:00 UTC.

So if Date.now() is in milliseconds guess I will have to do a conversion for every `modified_timestamp` field. That's doable but why are we using the unix timestamp and not just what we get with javascript's Date.now()?

**Comment by jessica-azgs** [comment]
Oh and all the old spots use milliseconds for their modified_timestamps. We should have the project, dataset and spot `modified_timestamp` field be created the same way for all.

**Comment by jasonash** [comment]
OK, I thought we had agreed to use a unix timestamp when we first started the project. Let's just keep the thirteen digit integer. I will change to server side to match.

**Comment by jessica-azgs** [comment]
I don't remember if we had or not but I didn't realize one used milliseconds and the other seconds. I'm using whatever you get with `Date.now()` for project, dataset and spot modified_timestamps now. (That's how it always was with the spot modified_timestamp.) If you want me to change it I can.

**Comment by jasonash** [comment]
No, we can use milliseconds if that is easier for you. It looks like javascript might be the only modern language to use milliseconds though. I'm not sure why they chose that route. I can just do a date()*1000 to get a rough equivalent.

**Comment by jessica-azgs** [comment]
Yeah, thanks Javascript. It not that much more difficult for me to do the conversion client-side before I sent it to you. We just already have all of the old spots in milliseconds.

**Comment by jasonash** [comment]
Yeah, it's a toss-up. All of the old spots (from the app) are in milliseconds. All of the old spots from shapefiles are in seconds. I'm assuming that the shapefile spots won't ever be updated per-se, so I suggest staying with milliseconds. I'll change the shapefile code on the server side accordingly.
