### ISSUE TITLE
KoBo Form Changes

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#236]
@zmichels @JEAndrew These are the notes I took on things Basil and Doug want to have changed in KoBo forms. Hopefully they make sense to you so one of you can make the changes.

- Rock Units - only  abbreviation should be required
- In Linear orientation - rake needs rake direction and rake calculated needs to default to 'No'
- In Tabular feature type, movement - movement justification needs to have sheer sense indicator
- In Tabular feature, sheer or fault zone - need unkown for type
- In Tabular Zone, fault zone/sheer zone type - need coaxial
- In Planar feature type need sheer zone, which pops up another field with more detail about sheer zones
- Planar feature - need movement amount qualifier (min, max, estimate)
- 3D Structures, folds, dominant fold geometry - need a new option for interfolial and add Other option
- 3D Structures, boudinage - copy fault movement for sheer sense

**Comment by JEAndrew** [comment]
I can update these this afternoon


-joe



________________________________

**Comment by JEAndrew** [comment]
In Linear orientation - rake needs rake direction


does this refer to up & down, cardinal direction or azimuth?


the question hint says 0-180, implied right-hand rule?





________________________________

**Comment by jessica-azgs** [comment]
I'm not sure if @panamint55 or Basil checks these issues. One of them will need to clarify. I have no idea.

**Comment by panamint55** [comment]
I do an will soon.  I think basil had the best idea on this over the weekend.

Doug

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

From: Jessica Good
Reply-To: StraboSpot/strabo-mobile
Date: Tuesday, March 29, 2016 at 12:38 PM
To: StraboSpot/strabo-mobile
Cc: Doug Walker
Subject: Re: [StraboSpot/strabo-mobile] KoBo Form Changes (#236)


I'm not sure if @panamint55<https://github.com/panamint55> or Basil checks these issues. One of them will need to clarify. I have no idea.

**Comment by JEAndrew** [comment]
I made the changes to kobo forms.


For Movement question (faults, sz, boudins) can we simplify the choice list by deleting NE, NW, SE, SW choices?


-joe

**Comment by panamint55** [comment]
I think Basil liked those in there.  Maybe we should bring this up on the Wednesday call this week.

**Comment by jessica-azgs** [comment]
Thanks @JEAndrew. I updated these in the app. They'll show up in the next version I release later today. Can you double check them then?

**Comment by JEAndrew** [comment]
A few things didn't workout correctly (mostly skip logic). I have just fixed them in Kobo forms. Sorry.

**Comment by jessica-azgs** [comment]
I pulled in your updates to the latest version, 0.10.4.


Jessica Good
GIS Applications Developer
Arizona Geological Survey
http://www.azgs.az.gov/
jessica.good@azgs.az.gov
