### ISSUE TITLE
Sample Prefix and Numbering

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#237]
We need to have the option for sample numbering put into the preferences.  Sample numbers can also include letters as per the way IGSNs are done.

**Comment by jessica-azgs** [comment]
Wouldn't the sample number be different for each sample though? Or do you want it to be like the Spot number and the app would increment the number automatically? But in that case it would have to be a number and not include letters.

**Comment by panamint55** [comment]
Like spot number.  We get a 3 character prefix for IGSN, and then 6 characters after that.

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

From: Jessica Good
Reply-To: StraboSpot/strabo-mobile
Date: Monday, April 4, 2016 at 12:09 PM
To: StraboSpot/strabo-mobile
Cc: Doug Walker
Subject: Re: [StraboSpot/strabo-mobile] Sample Prefix and Numbering (#237)


Wouldn't the sample number be different for each sample though? Or do you want it to be like the Spot number and the app would increment the number automatically? But in that case it would have to be a number and not include letters.

**Comment by jessica-azgs** [comment]
Done in commit 83387b6.
The already existing `Sample Prefix Label` can contain any number of characters but the field hint now says to use exactly 3 characters for an IGSN code. Also added the field `Starting Sample Number` which is a numeric field and can contain any number of digits however the field hint states that exactly 6 numbers should be used if creating an IGSN code. The `Starting Sample Number` field automatically increases by 1 every time a new sample is created.
