### ISSUE TITLE
Offline Maps: Deleting Map Crashes App

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#238]
Crashes every time an offline map is deleted on iOS.

**Comment by panamint55** [comment]
This does it all the time, logged in or not.

Doug

**Comment by jessica-azgs** [comment]
Calculating the total size of the maps was crashing the app. This should be fixed now since I no longer calculate or display a total size of all offline maps to users. Worked fine for me with the Field Camp 2016 project. Deleting does take awhile with a large number of tiles though because the app needs to make sure each of the tiles it is deleting is not needed for another map.
