### ISSUE TITLE
Add Tags

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#244]
Add the ability to tag Spots as well as sub-Spot-level features (orientations, 3D structures, samples and other features) with a label. This should be able to be done from a main menu item called Tags and from a tab in each spot called Tags. For sub-Spot-level features need to be able to tag these from within each feature. And even for Spots we need to have a way to tag features without going to the Tags tab (probably put in 3-dot menu at top right corner).

See the KoBo form Tags to edit the fields to for a Tag Group. [This issue](https://github.com/StraboSpot/strabo-mobile/issues/235) is specific to the Categorization field.

Are we calling these Tags, Tag Groups, Groups, or something else?

**Comment by jessica-azgs** [comment]
Implemented at the Spot-level only so far.

**Comment by jessicagood** [comment]
feature-level tags added with commit bf2c74f6c41a62c44efd7ab1503306a16d638cf0
