### ISSUE TITLE
Add Ability to Specify Database Endpoint

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#248]
Can we add an option to the "Miscellaneous" page to specify the database endpoint?

It would default to "http://strabospot.org/db" but having the ability to specify the endpoint will allow people at field camp use an instance of the Strabo database in the field. My plan is to duplicate the Strabo database and web page on a server for Doug to take to KU field camp. In this case, the database endpoint would become "http://192.168.1.55/db" or similar.

**Comment by jessica-azgs** [comment]
Sure, I can work on this next week.

**Comment by jessica-azgs** [comment]
Added in commit aa4b38bad78707935f1ac154560151ec8cdba4fe. @jasonash You can test it out in version 0.12.0 or above.

**Comment by jasonash** [comment]
Works great! Thanks!
