### ISSUE TITLE
Tab Order

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#258]
1. Spot
2. Orientations
3. 3D Structures
4. Images
5. Tag Groups
6. Samples
7. Other
8. Nest
9. Inferences

**Comment by jessica-azgs** [comment]
Changed with commit 879abb9

**Comment by btikoff** [comment]
How about this for order?

Spot
Orientations
3D Structures
Images
Nesting
Samples
Other Features
Inferences
Tags

**Comment by panamint55** [comment]
Sure.


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessicagood** [comment]
closed with commit 5d33436
