### ISSUE TITLE
Upload Error With Field Camp Data

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#271]
From @egbunse:

Doug and I are working on transferring the field camp datasets into accounts on the online server for testing the plug-in (the API for the offline server wasn't compatible with my plug-in). 
We ran into an issue with uploading datasets for one student and weren't sure why the app is behaving this way. The attached picture shows the dialog box messages we're getting. Its odd, because when we checked this project in the database, all three showed up complete. I checked that spot (F-M/R) and it is the last in the dataset with any images associated with it. 
Also got the following error for a couple of users Blue Ridge datasets: Server error: Type Error: undefined is not an object (evaluating 'spotNoImages.properties'  and am unsure what to do about it.

![20160803_134559](https://cloud.githubusercontent.com/assets/1493985/17412625/8a6c8b04-5a32-11e6-8399-b047a7c12dd5.jpg)

**Comment by jessica-azgs** [comment]
From @egbunse:

Doug and I got two iPad copies made with iMazing and put them into the shared 'Strabo Debugging' Dropbox folder. The one with 8 at the beginning had the server error and the one with 19 had one spot in the Temple Canyon dataset not upload to the online server. We're working on another iPad with the same server error as 8

**Comment by jessica-azgs** [comment]
@egbunse I'm not too clear on the steps you took to get the errors you're talking about. I tried uploading both the Blue Ridge and Temple Canyon datasets in iMazing backup 19 and didn't get any errors. I'll look at the iMazing backup 8 next but could you elaborate a little more on the exact steps and errors you're getting?

**Comment by egbunse** [comment]
Sorry, Jessica. I guess I wasn't clear on which ones had issues. #19 simply was not loading all spots to the server on the Temple Canyon dataset. There should be 130 spots, but no matter how many times I tried to re-upload it would only push up 129. It doesn't throw an error, but it might be a problem with a spot.
The server errors I talked about are occurring on #8 when trying to upload the Blue Ridge dataset to the online server or the field camp offline server. When I push the button to upload the dataset (this happens with it being the only dataset selected or with all three selected), the server error button will pop up on the iPad.

**Comment by egbunse** [comment]
I've gone through all the iPads and have one more account that is throwing the same server error as 8 on the Blue Ridge dataset. Doug can put it on iMazing a little later if you'd need it.

**Comment by jessica-azgs** [comment]
I was able to fix the issue with `Server error: Type Error: undefined is not an object (evaluating 'spotNoImages.properties' ` that happened with fc8.  This will be in the next update. The app was trying to upload a spot that was deleted but still in the list of which spots were in that dataset. Not sure why the spot didn't get deleted out of the list at the same time, maybe the app crashed exactly then. Either way I added a bit of code to check for this problem on the rare occurrence that it happens again.

I'm still looking at the problem with fc19 in that not all the spots are uploaded. I can see that 130 spots are being sent to the server even though you only see 129 when you look at strabospot.org. Now I'm trying to figure out which spot is failing. But we may need your help on this one @jasonash.

**Comment by jessica-azgs** [comment]
Interestingly if I try to open the Excel file at strabospot.org with the 129 points for the Blue Ridge Dataset it's corrupted and won't open. The map displays fine though. Same with the Temple Canyon dataset - the Excel file says 'we found a problem with some content ...' and tries to repair it but can't. The Twin Mountain dataset opens fine though.

**Comment by jasonash** [comment]
I'll take a look at the raw data and see if I can find the issue.

**Comment by jessica-azgs** [comment]
It is `14660229136082` that is not uploading:

```
        "type": "Feature",
        "geometry": {
            "type": "LineString",
            "coordinates": [[ - 105.30405996582, 38.563481643364], [ - 105.30399961611, 38.563572874438], [ - 105.3039057388, 38.56361481972], [ - 105.30384002468, 38.56369661295], [ - 105.30388964554, 38.563793086896], [ - 105.30382259032, 38.56384132382], [ - 105.30371530196, 38.563897949734]]
        },
        "properties": {
            "date": null,
            "time": "2016-06-15T20:35:13.000Z",
            "id": 14660229136082,
            "name": "QS",
            "modified_timestamp": 1466023269612,
            "trace": {
                "trace_feature": true,
                "trace_type": "contact",
                "contact_type": "metamorphic",
                "metamorphic_contact_type": "btwn_2_dif_mm",
                "trace_quality": "known",
                "trace_character": "sharp"
            },
            "self": "http://strabospot.org/db/feature/14660229136082"
        }

The date is null for reason so the server must not like that?

**Comment by jasonash** [comment]
Ah, yes. That's the issue. Neo4j HATES null values. Is this something you can fix, or should I try and fix it on the server side?

**Comment by jessica-azgs** [comment]
I can fix it for this client however, it's probably still good to have a check for it server-side, if the server isn't going to like it. Theoretically there could be another client (since the API for the server is open) that uploads a null value and at the very least an error message would be good. Though if a value exists in 'time' and not in 'date' for example the value could just be copied over. Otherwise it could default to "today's" date. 

There should really only be one date field but they have to be separate user inputs so they started out as two fields and I never changed it.

**Comment by jasonash** [comment]
OK, I'll work on adding checks to the API. It shouldn't be too difficult to roll over each parameter and discard if null.
