### ISSUE TITLE
Trace Fields

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#279]
Notes from Idaho fieldtrip:
- For trace feature under contact need more info under depositional - unconformity, disconformity, buttress and angular.
- For metamorphic change to isograd.
- Under trace type add unconformity.
- Trace type add cross section

**Comment by jessicagood** [comment]
From @panamint55:
- Trace quality should show up if trace is chosen.
- Trace Character should also show up if trace feature is selected.

**Comment by jessicagood** [comment]
See the KoBo form to make these changes.

**Comment by jessicagood** [comment]
@panamint55 I know you just edited the Trace form so can we close this issue?

**Comment by panamint55** [comment]
Yes.


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************
