### ISSUE TITLE
Polygon Feature

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#286]
Note from Idaho fieldtrip: For polygon features instead of just having rock unit have a select field for the type of feature the polygon is representing. If someone could create me a KoBo form I could try to get them in next week. The choices may need to be refined and there may be other fields following depending on which field is selected. @JEAndrew maybe you could help?

Surface Feature Type:
- rock unit
- contiguous outcrop
- geologic structure
- geomorphic feature
- anthropogenic feature
- extent of mapping
- extent of biological marker
- subjected to similar process
- gradients 
- other

**Comment by jessicagood** [comment]
Added with commit ecd1c93 however what exactly these fields should stay still needs to refined.

**Comment by jessicagood** [comment]
@panamint55 Any ideas on this list?

**Comment by jessicagood** [comment]
There is already a KoBo for for these fields it just needs to be looked over.

**Comment by panamint55** [comment]
Can someone doing KoBo - Joe, Zach, or Randy, look at this?

**Comment by JEAndrew** [comment]
This kobo looks fine. Sorry Jessica that I missed the email to create it.
