### ISSUE TITLE
Nesting Tab

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#288]
The nesting tag handles 2 things:
1. Continous Nesting
2. Displaying parent and child spots

Continous Nesting: Turn on and Strabo keeps track of all Spots saved. When it is turned off Strabo makes a polygon using these tracked Spots. The Spots are either the vertices of the polygon or within the polygon. What if there are only 1 or 2 Spots tracked?

Display Parent and Child Spots: Calculate the parent, grandparents, etc Spots and the children, grandchildren, etc Spots and display. What about sibling Spots? Use image basemaps and radius of Spot (if a point).

**Comment by jessicagood** [comment]
@panamint55 @btikoff When Strabo is gathering the nest, if polygon B is completely inside polygon A I understand B to a child of A. However what if polygon B overlaps polygon A only a little? Or a lot? How do you determine the parent/child relationships for intersecting polygons? At the moment I'm ignoring intersecting polygons unless one is completely within the other but how do you want me to handle this situation?

**Comment by panamint55** [comment]
We will talk about this over the weekend.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************
