### ISSUE TITLE
Question about tags section of project json

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#290]
@jessicagood ,

I'm having trouble understanding the tags section of the project json.

See the attached image. 
![tagsquestion](https://cloud.githubusercontent.com/assets/7904402/18208588/a000e1ac-70f5-11e6-8b98-b686fce9ea9e.jpg)

I understand the "spots" section, but the "features" section is a multi-dimensional array of spotids. Can you clarify what the purpose of the multi-dimensional array is?

Thanks,

Jason

**Comment by jasonash** [comment]
OK, after looking at this a little more closely, it looks like the "features" top-level array refers to a spot, while the sub-members refer to "features" which could be orientations, samples,  or other_features. Is this correct?

**Comment by jessicagood** [comment]
Yes, that's exactly correct.

The new features object in tags had to be completely separate from the
spots array since a feature may be tagged but not the spot. And using the
spot id for the key in the features object helps to quickly get to all the
tagged feature ids for a particular spot.

**Comment by jasonash** [comment]
OK, this sounds good. I'm slowly iterating through the json to create unique nodes for searching. I'll make sure to break out the features so that they are searchable.
