### ISSUE TITLE
Compass v. 14.4

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#291]
OK.  a few things with this morning's testing
1. my iphone should not be used for testing, so all this from the new ipad.  My iphone seems inconsistent 
2. It seems good when locked in portrait in the usual/standard orientation
3. When unlocked, it seems fine whether the screen rotates or not.  This needs more testing, but that seems to work fine. 
4. The compass can vary up to 20 degrees on the same surface
5. Locking in a different orientation causes problems, typically 90 or 180 degree rotations of dip direction.

I am not sure the magnetometer and accelerometer reorient the same way at the same time every time the screen reorients.  Is this a known issue?  There also seems to be a relative orientation issue when the screen is locked in different orientations.

**Comment by jessicagood** [comment]
Once the compass button is pressed begin to watch the compass orientation and acceleration every few seconds and display in a modal. Give the user an accept button to accept the current values and then stop watching the compass and acceleration.

@panamint55 How often did you want to grab a new orientation and acceleration? 2 seconds or .2 seconds?

**Comment by jessicagood** [comment]
added with commit 5998bb6c2f790cc974cca7eb1bb40cbf8a7dbcb7

**Comment by panamint55** [comment]
This is a great improvement.  I think 1 second might be better, but 2 is fine.  Also, this seems to solve all problems with compass orientations.  It seems to keep stuff updated at you rotate the compass.
That said, the plunge direction now seems backwards of what it was.  Can you look at this?

**Comment by jessicagood** [comment]
I didn't change the math so I'm not sure what's going on. Do you see something wrong with the math here? https://github.com/StraboSpot/strabo-mobile/blob/master/www/app/spot/orientation-data-tab.controller.js#L99

**Comment by jessicagood** [comment]
Changed watch frequency to 1 second with commit 9572f30. According to @panamint55 the plunge seems to be fine actually.
