### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#292]
Noah McLean got his UDID in for the app store and downloaded strabo.  He has had problems with the login.
1) Creating a login at noahmc@ku.edu with a password just got a spinning circle and never gave the regular screen.
2) He can login at strabospot.org no problem.
3) When he logs in he can manage data
4) When he tries to go to the online app it throws an error (at strabospot.org)
5) I can log in on his phone without issue
6) When you stop straboapp and restart on his phone he is sometimes shown as logged in.

**Comment by panamint55** [comment]
OK, the problem was the login creation does not have a message that the new user has to respond to an email verification.  Also, the link does not show up in apple mail on an iphone.  Both should be easy fixes.

**Comment by jasonash** [comment]
When you create an account at Strabospot, it displays the following message indicating that you need to verify your account:
![screenshot 2016-09-07 11 16 58](https://cloud.githubusercontent.com/assets/7904402/18319824/02268a30-74ed-11e6-8b43-65ba8d058637.png)

Can you elaborate how the link isn't showing up? Do you mean that the email is blank?

**Comment by panamint55** [comment]
Does this occur on the mobile app as well?

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessicagood** [comment]
The mobile app just directs you to the webpage to create an account.

**Comment by jasonash** [comment]
Yes, the mobile app just opens a browser to the strabospot.org signup page.

**Comment by panamint55** [comment]
OK, I will look into this again with Noah.  Sorry I cluttered this up, go ahead and take out the issues and I will see what exactly is happening.  Sorry again.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************
