### ISSUE TITLE
Data Model Question - nest vs nests 

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#293]
@jessicagood I've been working on the backend re-write and I notice that the data model sometimes has a "nest" property and sometimes has a "nests" property.

See the following example:
https://gist.github.com/jasonash/74e59bf976b0e197a8aa0b3a9190abd6

On lines 74 and 647, the property is called "nests" and is a multi-dimensional array.
On line 524, the property is called "nest" and is a simple array.

Is this the expected bahavior? Can you elaborate on when to expect the different properties?

Thanks,

Jason

**Comment by jessicagood** [comment]
Are you getting `nest` or `nests` properties with any data from a new version of the app? In version 0.13.9 I got rid of nest/nests as a property and it is now calculated based on geometry but not stored anywhere.

**Comment by jasonash** [comment]
@jessicagood These features were created with 0.14.0

I will try updating to see what happens.

**Comment by jasonash** [comment]
@jessicagood I just updated to 0.14.4 and I get the same results. Maybe I need to recreate my spots?
I did an uninstall/re-install and then re-downloaded my project and the "nest"/"nests" properties are still on lines 74,524, and 647. Are you keeping all properties downloaded from the server?

**Comment by jessicagood** [comment]
I'm not checking or deleting the properties downloaded from the server so they're just going to hang around and not be used if they come back from the server.

**Comment by jasonash** [comment]
OK, I just wiped out all of my data on the server and re-installed version 0.14.4.

I'm still getting "nests" properties in the resulting JSON. 

See here:

https://gist.github.com/jasonash/f56b8ed0b8d79ef4b41c6e7107ff1415

On lines 74 and 231 there are "nests" properties containing sub-properties {"name":"Some Spots"} and {"name":"More Spots"}. I did not enter these properties, so I'm not sure where they are coming from.

**Comment by jessicagood** [comment]
This is the JSON when you're uploading a new spot to the server?

**Comment by jasonash** [comment]
Yes, I cleared out all of my data from the server, installed 0.14.4, and pushed up two spots. 

This is the resulting JSON:
https://gist.github.com/jasonash/f56b8ed0b8d79ef4b41c6e7107ff1415

**Comment by jasonash** [comment]
Re-installed on new device and the nest/nests properties went away. There must have been some old data hanging around on my device. Will close.
