### ISSUE TITLE
Tagging on the map and creating a tag group with the"Add Tag(s) to Spot(s)" dropdown 

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#296]
Tagging on the map and creating a tag group with the"Add Tag(s) to Spot(s)" dropdown

**Comment by panamint55** [comment]
When you circle spots to tag them, the tag list comes up.  At that point, you can add an existing tag and it goes to all Spots.  This is good.

You can also create a new tag, but then after you do this new tag is not applied to the spots you have selected.  You have to either redo the selection or add from a list.  I think they should automatically get the tag if you 1) circle them, and 2) then create a new tag.

**Comment by jessicagood** [comment]
fixed with commit 528c72f1f295ff9fbaf3d4a748bc15bbd93e3020
