### ISSUE TITLE
Fold Type required

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#298]
When I put in a new spot and I select the 3D structure tab it gives 4 options.  If I hit the "fold" option and then immediately use the back arrow entering nothing it works and I can go back to the map.  If I reopen the same spot, then it starts giving a warning "fold type required!"  If I hit any of the other options (e.g., fabric) same behavior.  I can go out of the dialog but reselecting a spot gives the error about the 3D data type.  you must delete the spot to clear the error.

**Comment by jessicagood** [comment]
Good catch. Fixed with commit 4175246.
