### ISSUE TITLE
Testing the New Tags and Relationships Items

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#299]
@KendriSalmans Could you help me out by running a bunch of tests on these new features I put out with 0.14.5? Test things that the user might not typically do as well as standard operations and make a list in this issue of what works and doesn't. Thanks!

**Comment by KendriSalmans** [comment]
Okay!

**Comment by KendriSalmans** [comment]
Hey @jessicagood , I'm going to start compiling a Doc with notes that I have on some of the features. 

Currently I am  using 0.15.1. 

I'll try to keep things short, include pictures when I can, and go over everything. 

https://docs.google.com/document/d/1u-1WBggQ8jkrgJbQ4xSemic-MwunReOHdnqL1hV4_Mk/edit?usp=sharing

**Comment by jessicagood** [comment]
@KendriSalmans While it looks like the issues you've added to the google doc are not specifically about tagging and relationships, which is what I was specifically looking to be tested with this issue, you have some good info here. Could you make sure that the issues you've written in the google doc are not already issues in GitHub (you can search by key words) and then add each issue as a separate GitHub issue? Thanks!
