### ISSUE TITLE
Inference Tab & Fields

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#303]
At the meeting in Kansas, there was talk about changing the name of the Inferences tab to X-Cutting.  Is this really what you want? Do you still want Rosetta, etc on a tab called X-Cutting? Would the name X-Cutting work for other geology disciplines for defining their relationships too?

**Comment by panamint55** [comment]
I am not sure what we need here.  We really need to get Basil and Randy to comment.  X-cutting is often a relationship, so maybe that stays with that tab.  Rosetta is more of a significance, so perhaps this could go on another tab or perhaps become a TAG.

**Comment by zmichels** [comment]
I like the idea of "Rosetta" as a tag.

On Sep 29, 2016, at 10:09 PM, panamint55 <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure what we need here. We really need to get Basil and Randy to comment. X-cutting is often a relationship, so maybe that stays with that tab. Rosetta is more of a significance, so perhaps this could go on another tab or perhaps become a TAG.

-

**Comment by panamint55** [comment]
We could have it as a pre-defined tag, as long as we do not have too many of these, and the user-defined tags would normally be listed first.

**Comment by zmichels** [comment]
I vote for Rosetta as a tag. If I had my druthers I would scrap it altogether and let users define such a thing if it is something they want to do in their workflow... cut down the clutter.
Probably not a popular opinion:
I think most users will likely have never called a station/spot a Rosetta (or even really work in this explicit way), and I doubt many people will use it whether it is a tag or a whole tab of options. A couple will perhaps... feels like less than 80% to me.

On Sep 30, 2016, at 3:44 PM, panamint55 <notifications@github.com<mailto:notifications@github.com>> wrote:


We could have it as a pre-defined tag, as long as we do not have too many of these, and the user-defined tags would normally be listed first.

-

**Comment by jessicagood** [comment]
Inferences tab was removed and replaced with a tab just for relationships. See commit 24f080bc401d14194fc3a34bb4d5b07c366889eb
