### ISSUE TITLE
Malpais Mesa Dataset Missing Geometry

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#315]
@jessicagood  I was just looking over the issues with Emily's Malpais dataset and I noticed that one of the spots is missing a geometry. This same spot has an image that is serving as a basemap, so all spots on that basemap are unable to inherit valid real-world coordinates.

Here is the raw JSON coming in from the (iOS) app:

https://gist.github.com/jasonash/66e10fb01da509354878840e8caeca79

The spot with no geometry is 14759496807822

I thought this might help with narrowing down issues with the dataset.

**Comment by egbunse** [comment]
@jasonash From looking at that, the spot you're referring to should be a point. I wouldn't know the pixel coordinates, but can check to see if it might be on one of the iPads later on today.

**Comment by jasonash** [comment]
The spot in question has no geometry at all, but I'm assuming it should have real-world coordinates, not pixel coordinates.

**Comment by egbunse** [comment]
Yeah, I see what you're saying now. It is the "real world" spot which has the image basemap for the next few spots.

**Comment by egbunse** [comment]
@jasonash I'm not sure how I would go about adding in this spot's geometry?

**Comment by jasonash** [comment]
@egbunse I'm assuming you could download the project into the app and add the geometry on the spot page?

**Comment by egbunse** [comment]
Looking at the dataset on the iPad, the spot in question no longer has any information associated with it except date and time (it looks like from the earlier JSON read-out that it should have an image called "Facing SE." There also isn't an option for assigning it a geometry on the app and I think this might be because it doesn't have coordinates associated with it. Not sure if this is worth keeping anymore?

**Comment by jasonash** [comment]
@egbunse If you decide to delete spot 14759496807822, you'll also have to remove these spots:

14759497494344
14759502586611
14759504103125

These three reside on the  (now missing) image basemap associated with spot 14759496807822. The app should probably do this automatically in the future, or at least check to make sure that basemaps still exist before uploading.

**Comment by egbunse** [comment]
@jasonash If I were to re-add the missing image used as a basemap and then assign that spot an approximate lat/long and geometry do you think that would work, or would the connection to those other three spots not be retained?

**Comment by jasonash** [comment]
@egbunse You could try that... though I'm guessing the id assigned to that new image would be different. I would have to go in and manually change it.

**Comment by jasonash** [comment]
@egbunse I would suggest making a good known-working copy of the project in iMazing before attempting any changes.

**Comment by egbunse** [comment]
@jasonash I found the spot with the image on the iPad I was originally working on that day. I assigned it a geometry through assigning lat/long and have been trying to upload it to the strabospot.org/db server, but every time I get a failure to load one image. Should I attempt the test account or the newer server?

**Comment by jasonash** [comment]
@egbunse The new backend is down for the moment. Have you tried deleting the project from your account first before uploading?

**Comment by egbunse** [comment]
@jasonash I had not tried that yet and just did several times. The result was that it will say it is only uploading 3 images (one or two of which usually fail) out of the possibly 195 that I know should be on there (which should be missing if the whole project is deleted off my account). I've also got anywhere from 32-179 features (there are 171 spots).

**Comment by jasonash** [comment]
@egbunse OK, I put the new backend back up. Why don't you upload your project there (under your account) and I'll transfer it to Android and push it back up to strabospot.org.

**Comment by egbunse** [comment]
@jasonash still have 2 images failing on this iPad.

**Comment by jasonash** [comment]
@egbunse Did you try multiple uploads to the new backend? It sounds like the iPad is timing out on the images, which is expected. You should try uploading multiple times to catch the few that are missing. Short of that, I'm not sure what you could do.

**Comment by jasonash** [comment]
You could also make an iMazing backup of the good project and put it up on Dropbox. I can restore from that here and place the good project back on strabospot.org

**Comment by egbunse** [comment]
@jasonash I did try multiple uploads (I usually just keep hitting upload until it is successful), but those 2 images are stubborn. I have class with Doug here in a bit so we'll try and get an iMazing back up made and available to you sometime in the early afternoon!

**Comment by egbunse** [comment]
@jasonash Doug just got the copy put on Dropbox. He says it is in the "Emily" folder and is the 15.4 version. Let me know if there's anything else I can do.

**Comment by jasonash** [comment]
OK, I'll see if I can get it up to strabospot.org

**Comment by jasonash** [comment]
@egbunse OK, I was able to upload the project to your account at strabospot.org.

Your project was still missing an image file for spot 14757900898868. To remedy this, I just deleted the image from the spot.

I hope this helps. Please let me know if you need anything else.
