### ISSUE TITLE
Need Database Endopoint Changed

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#318]
@jessicagood I have enabled TLS encryption on the server for HTTPS traffic. At first, I forced all traffic to HTTPS, but the app doesn't seem to handle 301 redirects correctly. If I manually change the endpoint to https, everything works fine. Can you change the default app Database Endpoint to https://strabospot.org/db ? We'll have to remind people to upgrade as soon as possible. Right now, I've relaxed the server so http traffic is again working, but I would like to move away from the unsecure connection.

**Comment by jessicagood** [comment]
Done in version 0.17.3
