### ISSUE TITLE
Edited geometries not being saved from map edits

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#320]
While working on the live database connection, I realized that geometry edits made in the map interface aren't getting saved to the LocalStorage factory when clicking the "Save Edits" button. Basically, if you edit a geometry in the map, click "Save Edits", and then close the app and reopen it, the changes won't be saved. 

I tracked the problem down to line 104 of map-draw.factory.js. The original line is:

`var spot = SpotFactory.getSpotById(e.target.get('id'));`

but doing this is actually making changes to the SpotFactory.spot, so when it gets to SpotFactory.save, it appears unchanged and therefore isn't saved to LocalStorage.

The above line should be changed to:

`var spot = JSON.parse(JSON.stringify(SpotFactory.getSpotById(e.target.get('id'))));`

This will deep clone the object rather than referencing it and will make the SpotFactory.save() function see the spot as changed and save it accordingly.

I have made this change in my branch, but I thought I would note it here to make sure it makes it to production.

**Comment by jessicagood** [comment]
Good find! I'm surprised no one, including me, didn't notice that the edits weren't actually being saved.

I pushed this change into the master and incremented the version. Thanks!
