### ISSUE TITLE
Trace Character

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#322]
We need to add the Trace Character to the trace feature dialog.  This should be in the Kobo Forms.  This needs to be added.

**Comment by jessicagood** [comment]
I don't see any updates to the KoBo Forms for Trace Character. This part of Trace is the same as what's in the app already. Trace Character only shows up with the skip logic below.

![image](https://cloud.githubusercontent.com/assets/1493985/21652567/62e2f8ce-d26a-11e6-9bf3-9344c4138f09.png)

Should the skip logic be different?

I do see the other update to Trace where you changed 'Shear Sense' to 'Fault Type or Shear Sense'.

**Comment by panamint55** [comment]
OK, got it.  I made a mistake, and it is working correctly.  Sorry about that.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessicagood** [comment]
Ok. Do you still want the wording of 'Shear Sense' changed to 'Fault Type or Shear Sense'? If so I should probably change the next field from 'Other Shear Sense' to 'Other Fault Type or Shear Sense' so it matches.

**Comment by panamint55** [comment]
Lets talk about this tomorrow.  Can you bring it up at the start of the call?  This is the first thing I have found that seems odd.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************
