### ISSUE TITLE
Geologic Unit Tag: Absolute Age of Geologic Unit

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#323]
From Greg Walsh (U.S. Geological Survey):  I could not enter an age range, only a single age. This is problematic for some map units such as a Formation, named pluton, igneous suite, etc. with a range of ages.

![image](https://cloud.githubusercontent.com/assets/1493985/21697089/009cd3e4-d34e-11e6-94e3-7a1dc48d03d7.png)

**Comment by jessicagood** [comment]
Do we want to change this to a text field? Or it could be split into 2 numerical field that together would represent a range? Downside to a text field would be that searching on the field for a date would be harder.

**Comment by jessicagood** [comment]
@panamint55 What do you think?

**Comment by panamint55** [comment]
Here is tensor


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessicagood** [comment]
Fixed in commit 05116a6 with edits from @panamint55
