### ISSUE TITLE
dialing phone number and crashing on image import

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#326]
Using an ipad with ios10.2 a spot with a strabo identifier tries to diel the identifier as a phone number.  Also, the program crashes when trying to import images or take pictures.  See 0.11.17 file in debugging strabo folder.

**Comment by jessicagood** [comment]
See https://github.com/StraboSpot/strabo-mobile/issues/331 for the closed issue with photos.

**Comment by jessicagood** [comment]
Looks like commit 47c02665aa798eef1bbabae884f302b8bc76c893 fixed the phone number issue. Please let me know if you still have this problem.
