### ISSUE TITLE
Github link

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#329]
Should we have a link in the "About" page on strabospot to link to the github issue reporting?

**Comment by jessicagood** [comment]
It is on the bottom of the About page, under **Bugs, Feature Requests and Other Issues**. Do you want it moved?

If we move it up that would mean moving down the directions on how to install the app.

**Comment by panamint55** [comment]
Not sure, I will look.  Several people asked about this.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************
