### ISSUE TITLE
Exit tags

### ISSUE THREAD

**Issue by sarahpd** [StraboSpot/strabo-mobile#330]
Once you enter the "Tag" menu, the program requires you to enter a tag name. It would be helpful if you could exit without saving a tag if you decide you do not want to create a tag after all.

**Comment by jessicagood** [comment]
@sarahpd You may press the back button to exit the screen if you decide you do not want to create a tag. The app will only require a name if you have filled out other fields on the page. Otherwise it will exit without creating a tag.
