### ISSUE TITLE
Crashes every time adding photo

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#331]
User reports crash every time try to add a photo either from camera or photo library on iOS on ipad2 Air. I tried now on my iPhone 6, and also crashes. Crash happens the instant I click "go" after selecting from where to add a photo.

**Comment by jessicagood** [comment]
Happens on my iPad even though not updated to iOS 10.2. Happens with old Strabo version 0.17.7 and latest 0.17.11.  Doesn't happen on Android. Looking into it more ...

**Comment by jessicagood** [comment]
iOS started requiring new permission for use of the camera/photo library. Fixed with commit f642e268390af87077cd9a0b9e43dac7f52582eb and 8a9acf28194cf3d8432094d252c884c1cfa269ea.
