### ISSUE TITLE
What's the best way to add an image/map that isn't georeferenced?

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#332]
A Beta user asked about this, and I am currently having a similar need...

Example Scenario:
I have an existing map image or schematic figure, and I have no intention on digitizing its components or georeferencing it; however I want it to be associated with multiple spots/stations/observations that I will import to Strabo sing the Shapefile conversion tool. In my actual use case this is a schematic map from a publication. 

Want:
A way to add the image but not define its location explicitly (maybe its a schematic description of a process for example). Instead, I want to tag/link the spots to this image. I realize that I could upload the image with every single spot, but that doesn't seem like best practice. Moreover, maybe I don't want it popping up at every stop, but I want to be able to know about it and view it if/when I want.

Does this make any sense?

**Comment by zmichels** [comment]
One idea: Maybe we could expand the project descriptions to include images?

**Comment by jessicagood** [comment]
You could make a Spot that is not georeferenced (from the Spots page, not
the map) and add the image(s) to that Spot. You'd want to give that Spot a
good label and then you can use tagging or relationships to link it to
whatever other Spots or sub-Spot features you want.

On Jan 21, 2017 11:13 AM, "Zachary Michels" <notifications@github.com>
wrote:

One idea: Maybe we could expand the project descriptions to include images?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StraboSpot/strabo-mobile/issues/332#issuecomment-274278249>,
or mute the thread

**Comment by zmichels** [comment]
Good plan!

And, just checking here, but… currently any images need to be uploaded through a mobile device, correct (i.e., fails on browser “desktop” version)? Jason said he can try to upload images for me, but this plan isn’t sustainable because ultimately I am going to have a lot of them (a couple hundred maybe) for Basil’s WISZ project/talks… and they will come in waves as I complete the imaging, and then again as I try to annotate details or zoom into key areas at higher mag. Also, are images uploaded through a mobile device reduced from their original resolution? I ask because maintaining high resolution is important for details in these micrographs.




On Jan 21, 2017, at 2:46 PM, Jessica Good <notifications@github.com<mailto:notifications@github.com>> wrote:

You could make a Spot that is not georeferenced (from the Spots page, not
the map) and add the image(s) to that Spot. You'd want to give that Spot a
good label and then you can use tagging or relationships to link it to
whatever other Spots or sub-Spot features you want.

On Jan 21, 2017 11:13 AM, "Zachary Michels" <notifications@github.com<mailto:notifications@github.com>>
wrote:

One idea: Maybe we could expand the project descriptions to include images?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StraboSpot/strabo-mobile/issues/332#issuecomment-274278249>,
or mute the thread

**Comment by jessicagood** [comment]
Image uploading will work on the web version. That should be out soon. You can add to the discussion of the image resolution here: https://github.com/StraboSpot/strabo-mobile/issues/214
