### ISSUE TITLE
scale bar on image basemaps

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#333]

**Comment by jessicagood** [comment]
I have a scale bar almost working but could someone add the fields for the user to enter this data to the Image Properties KoBo form and let me know when it's ready? @JEAndrew @panamint55 @zmichels

I see a field for Scale of Overall Image and a field for Scale and type of object in image (m) right now. I'm not sure if you want to use those but if you do they'll have to be slightly modified anyway. We'll need the user to enter the full width of the image (a number field) and the units for the width (a dropdown box). I don't know what units you want to give as options but I'm sure it's more than just meters.  Thanks!

**Comment by panamint55** [comment]
I will do this a little later tonight.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by JEAndrew** [comment]
I added an image width and units to Kobo forms. I made changes in answers (fixing errors) to other kobos also.



________________________________

**Comment by jessicagood** [comment]
Thanks @JEAndrew. Only change I made to what you did in KoBo forms was to add validation so the width has to be greater than 0.

This has been added with commit 739bb3af531fc651512b8fbc2a10b292c7433c1b

**Comment by zmichels** [comment]
Just checking on this. I added an image along with the width of image view, and I set the image as a base map. I do not see a scale bar. Is this still in development? Just curious.

**Comment by zmichels** [comment]
Hmmm. Update. When I save and back out of the image details (where I add the scale)... I don't see any scale bar when I click the image. If I then open the details again, the units selection has unfilled itself... I set it again to "mm". Repeat... same thing. Any reason why it doesn't save that? Everything else is being saved.

**Comment by zmichels** [comment]
Just downloaded app again in case version wasn't latest. Now the units seem to stay filled in... still no scale bar. No biggie, but just was checking on this.

**Comment by jessicagood** [comment]
@zmichels I can't recreate your problem. It looks to be working fine for me - both saving the units and the scale bar showing up on the image basemap.

**Comment by jessicagood** [comment]
@zmichels Are you looking at the image as a basemap or just the slideshow of images on the Images tab?

**Comment by zmichels** [comment]
Ahhh. Yep. Sorry. Now with update I do see the scale bar when open the "map" (didn't before but musta been an older version I had). Is there a way to get it to show when just view the image, too? Maybe that's not something others want I guess... but I think I'd like to see the scale of someone specifies it even if not set to be a basemap.

**Comment by jessicagood** [comment]
@zmichels Glad you got it working. Not easy to put the scale bar as it is now in the image slideshow since it is tightly integrated with the map and map library. But if this is a significant issue you can make a new issue for it and we can address the priority of that feature.

**Comment by zmichels** [comment]
Ok. Thanks for clarification.
