### ISSUE TITLE
Add altitude to Spot

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#339]
From @panamint55

**Comment by jessicagood** [comment]
This doesn't seem to be working with Android.

Added with commit 993115c and even updated the [geolocation plugin](https://github.com/apache/cordova-plugin-geolocation) to 2.4.1 but Android is return `null` for the altitude.  Tested outdoors for perhaps a better GPS signal and tested with `enableHighAccuracy: true` but no success. Others seem to be having this problem but no working solutions. See http://stackoverflow.com/questions/36714293/cordova-plugin-geolocation-for-android-doesnt-return-altitude and http://stackoverflow.com/questions/31720388/cordova-geolocation-altitude-not-work

See if this works in iOS with the next release or on Android for anyone else. App attempts to grab the altitude when the Set to My Location button is pressed.

**Comment by jessicagood** [comment]
iOS is returning a number for altitude. Do we need to do any calculations to this number so it is more useful?

**Comment by panamint55** [comment]
No, that is all we need.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************
