### ISSUE TITLE
Live DB save not called

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#344]
@jasonash It looks like the Live DB calls are not being made when an individual relationship is saved nor when a tag is saved. Though it looks the Live DB call is being made when you enter the relationships page and the tags page but I'm not sure we need it there.

**Comment by jasonash** [comment]
@jessicagood I've moved the liveDB calls to the correct locations for tags and relationships. I also fixed the missing calls when tags and relationships were deleted. These changes are in commit  c7196c8
