### ISSUE TITLE
User Profile Image for WEB

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#346]
@jasonash Looks like the user profile image isn't coming in again. At least for me. But you had fixed this before so I'm not sure what's wrong now and I haven't looked at it yet.

**Comment by jasonash** [comment]
@jessicagood I did a fresh pull this morning and it looks like profile images are working correctly:

![screenshot 2017-02-10 08 23 00](https://cloud.githubusercontent.com/assets/7904402/22829944/689d1322-ef6a-11e6-85bf-5a7c038d0aa1.png)


I tried several user accounts and profile images worked for all of them.

**Comment by jessicagood** [comment]
yeah, looks like it is working now. I don't know what was happening before.
