### ISSUE TITLE
Add Logic to Form Input

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#35]
I added a few more sample hard-coded fields to the form input but the logic for these fields still needs to be applied. For example, the current fields in Spot Detail should only be shown if the planar Attitude Type is selected. There will be other fields for the other Attitude Types. See https://github.com/StraboSpot/Document-strabo/blob/master/fieldsAndAttributesKU.xlsx for other preliminary logic.

**Comment by ginxwar** [comment]
I've got lots of questions.  From my interpretation of the excel sheet, I'm assuming that for the attitude type of "planar", the attributes are:

plane_type
strike
dip
plane_quality
plane_facing
minor_fold_type
trend
plunge
rake
rake_azimuth
lineation quality
shear_sense
unit_name
unit_label

The attitude types of "linear" are:

lineation_type

The attitude type of "planar and linear" are:

planar_and_lineation_type (values are: crenulation cleavage and lineation, foliation and lineation)

I'm assuming that each spot can only have at most one attitude type?  In other words, if a user accidentally chooses planar as attitude type and begins to fill out the form, they can subsequently click on "linear" and populate linear attributes and the system would ONLY save the "linear" attribute information and disregard "planar" attributes.

Also, I'm assuming that the attributes for each specific attitude do not cross over.  In other words, only "planar" attitude types have strike and dip, but "linear", as well as "planar and linear" do not have strike and dip values.

**Comment by zmichels** [comment]
I will try to give a more in-depth response soon....

For the moment:
Only planar features can have an attitude measurement (combined strike and dip information).
Lineation orientations are communicated by trend and plunge, or by the rake of the lineation in a known plane (lineations are often linear fabric elements that reside *within* a foliation/planar fabric element...).
So some of the attributes you listed from the spreadsheet do not apply to planes, and are intended for lineations. I will try to further clarify later today.

**Comment by jessica-azgs** [comment]
This all needs to be specified in KoBo Toolbox first. See issue #78
