### ISSUE TITLE
Spot does not stay selected on map

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#356]
When you display a spot on the web version by selecting it from the spot list and then select the map icon, the spot does not stay selected on the map.

**Comment by jessicagood** [comment]
Fixed with commit 0c0adde.

A Spot will only be highlighted on the map as a selected Spot if you get to the map from the map icon within that Spot. If you click on the map in the dropdown menu no Spots will be highlighted on the map.
