### ISSUE TITLE
MOBILE PRIORITY: Significant Digits

### ISSUE THREAD

**Issue by rtwilliamsgeo** [StraboSpot/strabo-mobile#358]
Many places in the app (in this case strike and dip / trend and plunge measurements) we are showing too many significant digits. For the previous mentioned measurements, these should be rounded to the nearest whole number when displayed.

**Comment by jessicagood** [comment]
This is a duplicate of issue https://github.com/StraboSpot/strabo-mobile/issues/354. See comments there.
