### ISSUE TITLE
Startup Map View

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#36]
For now we should just zoom to the extent of any already existing spots when the app is started. Eventually we may want to open with the last used view.

**Comment by ginxwar** [comment]
see commit e42202720ed09842c2e5c90d3628981506be2b33

**Comment by jessica-azgs** [comment]
I think right now the start view centers on the first spot placed. I think it shoud actually just start at the user's location. If it can't get that it should just zoom to the extent of the spots.

**Comment by ginxwar** [comment]
9268113d0b5fbe0b9d468b15c418d87774404983 startup map view now checks geolocation first, then loads first spot if geolocation fails

**Comment by jessica-azgs** [comment]
Looks like this is now addressed in https://github.com/StraboSpot/strabo-mobile/issues/112.
