### ISSUE TITLE
MOBILE PRIORITY: Dip Direction

### ISSUE THREAD

**Issue by rtwilliamsgeo** [StraboSpot/strabo-mobile#361]
When measuring a plane, we need to change the label of "Dip Direction" to "Azimuth Dip Direction".

**Comment by jessicagood** [comment]
Changed with commit  3b893b6. @rtwilliamsgeo It seemed like this was just a simple KoBo forms change that I then pulled into the code. If it was supposed to be more than that let me know and reopen this issue. @jasonash Don't know if you need to know about this field change but just the label changed not the name of field.
