### ISSUE TITLE
on spot list make the "set list detail" automatically on

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#365]
On the spot list in the mobile app, and certainly the desktop, the "set detail list" should be automatically on.  I am not sure this even needs to be an option, and the spot list is not very useful without this.  

My suggestion is to always show the detail with things like images, orientations.  Also, the only option should be tags on or off, with option automatically selected to "on"

**Comment by jessicagood** [comment]
Fixed with commit 3b35d51. I didn't change the styling of the details but there might be a way to make it look a little better. You can re-download the latest version (0.18.8) to see the update.
