### ISSUE TITLE
Spot data label in orientations tab

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#366]
Could we (you) make the label field to show the type (planar or linear feature type) in stead of the label. The value 'Label' could be in also shown, but the planar or linear feature type is more important.

**Comment by jessicagood** [comment]
@JEAndrew The label for an orientation is taken from the feature type if no other label is entered by the user. So I think we have that already covered and with maximum flexibility for the user if someone does want to change the label to not use the feature type.

**Comment by JEAndrew** [comment]
For my data imported from shapefiles, everything says no label in orientations tab



________________________________

**Comment by jasonash** [comment]
Joe, this is the default behavior for the shapefile parser. I will change it to null for you to test.

**Comment by jasonash** [comment]
Joe, please try a shapefile upload again. I have removed the default "no label" value from the orientations.

**Comment by JEAndrew** [comment]
I'm on a roll today.  That didn't change anything with the label


The correct label from the feature type came up if I added a new spot to my uploaded data.


________________________________

**Comment by jasonash** [comment]
OK, Joe try your upload again. I think it's sorted out now.

**Comment by JEAndrew** [comment]
That appears to have worked.



________________________________
