### ISSUE TITLE
iOS 10.1 install fails

### ISSUE THREAD

**Issue by cashaw-mt** [StraboSpot/strabo-mobile#369]
Installation of Strabo-mobile 0.18.9 from https://build.phonegap.com/apps/1289076/share fails. Attempts on iPhone and iPad mini running iOS 10.1

Returns dialog: Unable to Download App "Strabo-mobile" could not be installed at this time.

**Comment by zmichels** [comment]
Have you registered your device with the development team? At this stage we still need to register devices with our provisional development license with Apple. In the near future (a few days or a week), the App should be available on the App Store. In the meantime, if you want to install Strabo ASAP, please send to me the UDID of the device you wish to add. Here are instructions for retrieving the UDID for your device:
https://www.innerfence.com/howto/find-iphone-unique-device-identifier-udid


You can email the UDID to zmichels@wisc.edu<mailto:zmichels@wisc.edu>


If you've already registered your device with us, please let me know.

Cheers,
Zach

On Apr 25, 2017, at 12:21 AM, cashaw-mt <notifications@github.com<mailto:notifications@github.com>> wrote:


Installation of Strabo-mobile 0.18.9 from https://build.phonegap.com/apps/1289076/share fails. Attempts on iPhone and iPad mini running iOS 10.1

Returns dialog: Unable to Download App "Strabo-mobile" could not be installed at this time.

**Comment by panamint55** [comment]
We can send out a test flight invitation.


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by cashaw-mt** [comment]
Thanks Zach & Doug. I can wait a week. If the App Store release is delayed I may proceed with the registration.  I would like a chance to test before field camp begins (15 May)!
