### ISSUE TITLE
difficult spot selection Android

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#376]
very difficult to select spots on map view using Android Samsung galaxy 7S

**Comment by jessicagood** [comment]
@JEAndrew Are you getting any of the popups on the map to show when tapping on a Spot? I can't get any of the touch events for popups on the map to register any more on my Galaxy S6 but the same events work fine on an emulator on the computer. Still looking into it.

**Comment by jessicagood** [comment]
Looks like it broke because of an Android update. Updating OpenLayers from 3 to 4 fixes the problem so I'm working on making this update and fixing the other things that break because of the update.

**Comment by JEAndrew** [comment]
Great!



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by JEAndrew** [comment]
Nothing happens when taking to click on a spot, but in edit mode I can easily move a spot or vertex on a line



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by JEAndrew** [comment]
One out of maybe 80 touches actually worked to select a spot



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jessicagood** [comment]
Fixed with commit b443632 (update to OpenLayers v4.2.0). Will be in next release.

Thanks for letting me know about this problem @JEAndrew!
