### ISSUE TITLE
Error on Offline Basemaps Screen

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#377]
The current phoneGap build (0.22.0) has a problem on the offline basemaps screen. It looks like the .js template isn't being parsed correctly. See attached image.
![offline_maps_error](https://user-images.githubusercontent.com/7904402/28434427-d880bd0c-6d54-11e7-8ba2-788e8d61960e.png)

**Comment by jasonash** [comment]
The same error occurs on iPad and Android.

**Comment by jessicagood** [comment]
@jasonash Hmm, I can't recreate on Android or in my dev environment. Was going to try iOS but I accidentally hit the button to upgrade the OS when I meant to cancel.

Anything else you can think of that can help me recreate. Maybe it's specific to a project? Or does it happen all the time?

**Comment by jasonash** [comment]
@jessicagood  I did a fresh install from the phonegap link (https://build.phonegap.com/apps/1289076/share) and logged in and created a new project. I clicked on the map menu and then clicked on the mapbox satellite layer. Then I clicked on save map for offline use. This is what generated the image above.

Strangely, I just tried the above and it is working fine now.

The reason I opened this ticket is that Allen Glazner reported the exact same problem, and provided this screenshot from iOS:

![img_2128](https://user-images.githubusercontent.com/7904402/28436119-6fc6dede-6d5b-11e7-89bc-ea97f1215a18.png)

**Comment by jessicagood** [comment]
Weird. I haven't updated the build in a few days so it's odd to get a different result. I'm not sure how to fix it if we can't recreate the problem. And the code for that page hasn't significantly changed since March so there must be something unique going on.

**Comment by jasonash** [comment]
Yeah, I don't think we should spend much time on it. Let's just keep this ticket so we have a record of it happening in case others report it.

**Comment by jessicagood** [comment]
@jasonash I figured out what this problem was. Fixed with commit a6762a8 and will be on v 0.24.0. On mobile the zoom levels aren't integer values necessarily so this was screwing up the calculation of the possible zoom levels to download when saving a map.
