### ISSUE TITLE
Error Loading List of Projects From Server

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#378]
From @egbunse: "However, I am getting an error after updating to 0.23. I already had a dataset pulled up on my Strabo Mobile app so I tested the date filtering with it. But then I logged out to see mess with filtering in another dataset and can log in to another account(s) but can't get the "select an existing project" part to work. I've tried it for two separate accounts with the same results: When I press the "select existing project" button, it spins a long time on "getting projects from server" and then gives me an error message "error communicating with the server; error loading the list of projects from server!" I've tried it on wifi and my 4GLTE connection here in the office, but as I say, I can log in (and see my profile pic), so I think it might be some issue with just the projects part. I'm using a Samsung S7Edge phone and I believe it is up to date on android. Any advice/ideas?"

**Comment by jessicagood** [comment]
I'm trying to recreate this but I haven't been able to yet. I've tried on my Samsung S6 and in my dev environment. Is it still doing this for you? Anything else you can think of that may help me recreate? @jasonash Could the logon request have been successful on your end but not the request for the list of projects? It all seems fine to me now.

**Comment by jasonash** [comment]
I just checked the server. Everything looks fine on that end.

**Comment by egbunse** [comment]
@jessicagood @jasonash I uninstalled and reinstalled it on my phone and everything seems to be working great now. Should have thought to do that sooner- sorry about that!  You can close this.
