### ISSUE TITLE
Plus Sign on Spots Page Doesn't Work

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#380]
When on the spots page and you click the plus sign, nothing happens. No modal is shown. The spot is actually added in the background but doesn't appear in the spots list. When you navigate away from the spots page to images and come back, the spots appear in the list. This was tested on iOS and reported by Virginia Toy.

**Comment by jasonash** [comment]
Fixed with  2d31953

**Comment by jessicagood** [comment]
Made the fix work with WEB with commit a595bab
