### ISSUE TITLE
Add save label to top bar next to back button

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#387]
When collecting data (an orientation for example) users often placed their devices down to more-closely examine things. If the device (iPad) went to sleep, any data saved on the current (orientation) page would be cleared and they would lose their progress. Maybe we should investigate adding a manual 'save' button or even add event handlers to each input to prevent this?

**Comment by jessicagood** [comment]
Added Save button (and Cancel button) to Orientations, 3D-Structures and Samples modals with commit 9802be2.
