### ISSUE TITLE
Add new tag "Rosetta"

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#389]

**Comment by jessicagood** [comment]
@btikoff All the other tags have a subtype under the main type. For example, under the Concept tag we have Geological Structure, Marker Layer, Deformation Event etc. Are there any subtypes you want under Rosetta?

**Comment by jessicagood** [comment]
Or should Rosetta be a subtype of Concept, Documentation, etc?

**Comment by jasonash** [comment]
Per Doug, Rosetta is its own supertype with no subtypes.

**Comment by jessicagood** [comment]
Thanks @jasonash. Added with commit 3fa0671
