### ISSUE TITLE
android webview version is different than Chromium webview

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#40]
When debugging strabo-mobile, we are debugging in the Chrome browser on the desktop, inside a Chromium webview container.

However, when we deploy this app to an android device, we are using the stock browser that comes on that Android device per manufacturer, not Chrome.  This is because the stock browser on the android device is independent of the Chrome browser.

Fixing this issue could also fix issue 38: https://github.com/StraboSpot/strabo-mobile/issues/38

This project looks like it should solve our problems:

https://crosswalk-project.org/
https://crosswalk-project.org/documentation/cordova.html

**Comment by jessica-azgs** [comment]
Crosswalk has now been integrated into Ionic CLI
http://ionicframework.com/blog/crosswalk-comes-to-ionic/
