### ISSUE TITLE
Redo Folds (per Basil)

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#401]

**Comment by jasonash** [comment]
Per Doug, Kobo form is done and can be imported into app at any time.

**Comment by jessicagood** [comment]
We now have a field named `s_fold`, `z_fold` and `m_fold` in the Fold, Linear Orientation and Trace forms. Before the latest updates to Kobo Forms `s_fold`, etc was only in Trace. @JEAndrew Were you working on this? Can we give the `s_fold`, etc in the Fold and Linear Orientation forms a new name? The label can stay whatever you want.

**Comment by jessicagood** [comment]
Actually never mind the last comment, the problem was that the field names were the same but the field labels were different. Two of the forms had used a label s-fold and the other form was s fold. I made all three s-fold. so we're fine now. No more changes need to be made for this issue.

**Comment by jessicagood** [comment]
Updated with commit 39d6250
