### ISSUE TITLE
Add "Nested spots to Stereonet" option

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#417]
For a given spot, if spot is polygon and has nested spots, add option in three dot menu to copy data to clipboard for stereonet.

**Comment by panamint55** [comment]
Also, you can turn layers off in the legend.  The spot or download or lasso should only take data in active layers.  For example, if I have an area with foliation and fault attitudes/orientation, I would like to turn off faults and only get the foliations into stereonet.

**Comment by panamint55** [comment]
I am not sure we have to do this before app release, but it would be nice.  Otherwise, what is working now is fantastic.

**Comment by jasonash** [comment]
Completed with commit 5947a5f03518a949dbb5e27459aae7d960e99f13
