### ISSUE TITLE
Deleting Spot from Spot Page Locks up app

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#420]
When on a spot and you click the trashcan icon to delete the spot, the app locks up.

I tested, and this bug was introduced with commit be6fbd60b72f52f21bf8d7bf41ad9c3b72e326c5 (fixed view history stack)

**Comment by jessicagood** [comment]
Fixed with commit 1045c208b20702273b1fae63975dc3523621a74b

**Comment by jessicagood** [comment]
Still a problem. From map make a new Spot. In Spot switch tabs then click delete Spot. App locks.

**Comment by jessicagood** [comment]
Fixed with commit c9d9682
