### ISSUE TITLE
Orientations: Trace

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#429]
From Vasilis Chatzaras & Nick Roberts: Trace feature option—should it include bedding?

**Comment by jessicagood** [comment]
@panamint55 Do you want this is in the new build?

**Comment by panamint55** [comment]
Yes it should include bedding and be in the new build.

**Comment by panamint55** [comment]
Yes

**Comment by NathanNovak** [comment]
fixed with commit 2db181cdf446f52020717c491aef8cc320c8a1ae
