### ISSUE TITLE
Folds KoBo Form Updates

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#430]
From Vasilis Chatzaras & Nick Roberts:
- Foliation associated with folds should be after competent/incompetent material, right before field notes.
- No amplitude option currently.
- Kobo forms need to hide irrelevant stuff.
-  “Folded layer thickness” should be “Folded competent layer thickness”, or have a dialogue box.

**Comment by jessicagood** [comment]
@panamint55 Do you want this is in the new build?

**Comment by panamint55** [comment]
Yes, if it has been corrected in Kobo.

**Comment by jessicagood** [comment]
@panamint55 It has not been fixed in Kobo Forms. I can do first and fourth bullet, if you want, but I wouldn't know what you want for the middle bullets.

**Comment by panamint55** [comment]
Fixed.  I do not know what the third/irrelevant stuff comment is about.

**Comment by NathanNovak** [comment]
fixed with commit 2b116cad9e004209790d83804c14c4ac17ef201b
