### ISSUE TITLE
3D Structures KoBo Form Fields Updates

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#432]
From Vasilis Chatzaras & Nick Roberts:
- If selected symmetrical, it still asks for movement directionit should not do this.
- How is “wavelength” different from “scale”? Right now it has both.

**Comment by jessicagood** [comment]
@panamint55 Do you want this is in the new build?

**Comment by panamint55** [comment]
Yes.


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
***********************************************

**Comment by NathanNovak** [comment]
@panamint55 I fixed the first part with symmetrical and the movement.  It now only displays movement if asymmetrical is selected.  With the second part, which one would you like to use?  Wavelength or scale?

**Comment by panamint55** [comment]
It looks like the skip logic is correct for the symmetrical - says only show if asymmetrical.

I removed the scale option.

**Comment by NathanNovak** [comment]
fixed with commit 5f1cf04780aa1f1f585d85d53a5111886a9c5d46
