### ISSUE TITLE
Fabric KoBo Form Updates

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#433]
From Vasilis Chatzaras & Nick Roberts:
- Right now, there is only kobo form info for toctonites—all the other categories are blank.

**Comment by jessicagood** [comment]
@panamint55 Do you want this is in the new build?

**Comment by panamint55** [comment]
Can you send me the form this is on?  I cannot find it.

**Comment by jessicagood** [comment]
@panamint55 This is on the Fabric Form. Only tectonites has has a few fields after it. The others do not.

**Comment by panamint55** [comment]
This is fine for now.  We can add more to the others eventually.

I changed this to Not Mandatory, so folks could just put in a label and a desription.

**Comment by NathanNovak** [comment]
fixed with commit 5d835194ae5cccd87f62db2c92cd1459466bd744
