### ISSUE TITLE
Tensor KoBo Form Updates

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#434]
From Vasilis Chatzaras & Nick Roberts:
- elliptical data  “preferred shape orientation” should be called “shape preferred orientation”

**Comment by jessicagood** [comment]
@panamint55 Do you want this is in the new build?

**Comment by NathanNovak** [comment]
fixed with commit 537ecaaa29f29ce21efe810b171a5bda68f77ca9
