### ISSUE TITLE
Project not saving

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#436]
Per @egbunse:

Projects aren't live saving because a project that I helped someone at the KGS start yesterday is gone today. I was under the impression that projects started on the online app were automatically saved.

**Comment by jasonash** [comment]
@egbunse Can you elaborate on how you are creating this project? Desktop projects are created on the "my data" page, which has nothing to do with live save. Are you trying to create a project in another way?

**Comment by egbunse** [comment]
@jasonash Yes, the account was new with no data added yet. So I had Jon click the red + on the "My Data" page. Then we opened the online app and created a few spots within the default dataset.

**Comment by jasonash** [comment]
@egbunse I am unable to duplicate this error. I create a new project, add spots via the desktop version of the app, and then close the browser. The spots are still there when I log back in. I'll leave this issue open and do more testing later.

**Comment by egbunse** [comment]
@jasonash I'm sorry! This ended up being a miscommunication. He had deleted it. You can close this.
