### ISSUE TITLE
Cannot "Set From Map" on a Copied Spot in Online App

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-mobile#440]
@panamint55 discovered this today: If you're on the online app and copy a spot then click "Set From Map," click the point, line, or polygon tool in the main map view and draw the feature it creates a new Spot instead of setting the coordinates of the copied Spot. @jessicagood I can demo this behavior if you need it!

**Comment by jessicagood** [comment]
Fixed with commit 63f7b01
