### ISSUE TITLE
Other Feature -> Geomorphic Misspelled

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#442]
Geomorphic is misspelled under Other Feature
<img width="763" alt="screen shot 2017-12-03 at 8 35 07 pm" src="https://user-images.githubusercontent.com/7904402/33557351-9de1da3a-d8cc-11e7-8d45-a1cea827f085.png">

**Comment by jessicagood** [comment]
Can you tell if anyone has used this field in the database? I'm thinking it's probably not used very much yet so I can just change it.

**Comment by jasonash** [comment]
It looks like there are four spots with "geomorhic" as other_feature->type, but three of those are in your and my test datasets... so really there is only one spot affected. I would go ahead and change it. I'll update the one spot manually.

**Comment by jessicagood** [comment]
Ok, thanks for looking. Fixed with commit b8e2f66
