### ISSUE TITLE
Sed: Carbonate colors disappear

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#445]
From @UASTeam: Carbonate colors disappear in the column after exiting/restarting the program (they’re there initially after adding the interval).

**Comment by jessicagood** [comment]
@UASTeam this is because of the skip logic you have for the Principal Dunham Classification in Sed Composition. You have this field only showing up if Lithologies = limestone or dolomite. Principal Dunham Classification should be a top level field in the Lithologies Composition tab (ie. not contingent on any other fields being answered, unless you want to also include those field in the Add Interval dialogue.) Let me know when you've updated the KoBo form as you want it and I'll pull it into the app.

**Comment by UASTeam** [comment]
I'm not sure I understand. The skip logic for the Principal Dunham Classification is equivalent for the Principal Grain Size, so I'm not sure what needs to be changed.

**Comment by jessicagood** [comment]
In Texture you have the Principal Grain Size field showing all the time (there is no skip logic for it). In Composition you have the Principal Dunham Classification field only show if the user selects limestone or dolomite in a field called Lithologies (the skip logic) but there is no way for the user to select this in the Add Interval dialogue.

So in Compositon we can't have the secondary field of Principal Dunham Classification filled out until the primary field of Litholgoies has been filled.

**Comment by UASTeam** [comment]
In terms of workflow, the dunham classification should only show up if the limestone or dolomite lithologies are selected, so having the skip logic of the Composition tab as it is now is correct and necessary. I suppose one way to solve this might be to set up composition tabs for each lithology making the composition selection a top level field. However, this might be a bit clunky unless the user can customize which composition tabs are displayed to cut down on amount of text on the page. I'll set up some kobo forms so we can test it out. Is there any other way to have my cake and eat it too (i.e. leave the dunham composition nested in the composition tab, but also solve the coloration issue)? Could it color based solely on the input of the Add Interval dialogue and ignore the composition tab?

**Comment by jessicagood** [comment]
Fixed with commit 1d64819ce9758e39d86d7ce886fb3545bf88424c by adding Lithologies to the Add Interval modal.
