### ISSUE TITLE
Sed: X-axis labels need to be visible when zooming

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#446]
From @UASTeam:  It would be helpful to add the grainscale labels (x-axis) to the top of the column, since we can zoom and pan through the column. If there’s a way to fix the x-axis to the bottom of the page when zooming that would solve this issue. We just need some way to directly/clearly display grain size.

**Comment by jessicagood** [comment]
Grain size is now displayed in a pop-up for each interval. Having the x-axis labels at the top of the column could mean that in a very tall column one may not be able to see the bottom or top x-axis and this way would look more cluttered. And we cannot fix the x-axis to the bottom of page as solution. @UASTeam are we good with the needed data being in the popups?

**Comment by UASTeam** [comment]
Yes, the popup solution is great.
