### ISSUE TITLE
Sed: Add interval modal buggy

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#447]
From @UASTeam:  Add interval dialogue seems a bit buggy (menus reappear after making selections, blank menus appear, menus appear in the corner).

**Comment by jessicagood** [comment]
@UASTeam Is this issue still happening? I can't recreate any of the weird actions you describe.

**Comment by UASTeam** [comment]
No, the issue seems fixed since the latest update.
