### ISSUE TITLE
Sed: Data consistency

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#449]
From @UASTeam:  It would be very helpful for selections in the add interval dialogue to auto-populate/transfer over to the sed lithologies tab to cut down redundancy.

**Comment by jessicagood** [comment]
@UASTeam: It looks to me like all of the data added in the Add Interval dialogue transfers over to the Lithologies tabs except the 3 fields below. Do you see any others?
- **Interval Type** and **Miscellaneous lithologies** aren't included in any of the Lithologies tabs. There needs to be fields for this data if you want them to carry over from the Add Interval dialogue.
- **Principal Dunham Classification** needs to be a top level field (as discussed in https://github.com/StraboSpot/strabo-mobile/issues/445)

Let me know when you've update the KoBo forms to put these fields where you want them.

**Comment by jessicagood** [comment]
@UASTeam **Interval Type** is still not anywhere in the 4 forms for the Lithologies tab. I'm guessing this should be in the Basics tab? The interval type is entered in the Add Interval dialogue but then there is no where for the field value to go or to view the field value again since the field is not in the Lithologies tab.

For example, if unexposed/covered is entered in the Add Interval dialogue for Interval Type there is no place to see this field again since this field is not in the Lithologies tab.

**Comment by jessicagood** [comment]
@UASTeam Also the lithologies field is a select one in the Add Interval dialogue but a select multiple on the Composition part of the Lithologies tab. This fields must be a select one in the Lithologies tab. But if you need to have the user be able to choose other lithologies that will have to be another field. Maybe this needs a primary lithology field and then a other lithology field?

**Comment by UASTeam** [comment]
I added the 'Interval Type' option to the Basics tab. And I changed the field in the add interval dialogue to 'Primary Lithology' and add it to the composition tab.

**Comment by jessicagood** [comment]
@UASTeam This should be fixed with commit 06074f5b780513f2da64b54140ba5fccd3a0c2a8
