### ISSUE TITLE
Sed: Carbonate Colors

### ISSUE THREAD

**Issue by UASTeam** [StraboSpot/strabo-mobile#457]
The coloration of the carbonate (limestone and dolomite) disappears after adding additional composition information in the composition tab. I suspect this relates to the select one lithology of the add interval dialogue vs the select many lithology in the composition tab.

**Comment by jessicagood** [comment]
@UASTeam Yes, this is was due to the select one vs. select many issues. It should be resolved with commit 06074f5b780513f2da64b54140ba5fccd3a0c2a8.
