### ISSUE TITLE
Sed: New X-Axis Organization

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#459]
From @UASTeam: Have multiple x-axes like in the following image
![image](https://user-images.githubusercontent.com/1493985/35304238-0dbac130-0052-11e8-97cd-46e4115bf7bc.png)

**Comment by jessicagood** [comment]
@UASTeam Do you still want the multiple axes or is having them all on one axis working for you better now?

**Comment by UASTeam** [comment]
Lets do the multiple axes and try it out. I think it will be a cleaner presentation.

**Comment by jessicagood** [comment]
@UASTeam I'll start working on this but I am worried how this will look at on a small device, like a phone, with the X-axis being so big (tall). If you're trying to look at the lowest x-axis you won't be able to see many intervals unless you're really zoomed out, and then the text may be too small to read. @btikoff or @panamint55 Having used the app on a phone a lot do you have any thoughts on this?

**Comment by jessicagood** [comment]
@UASTeam Added with commit 31c9d69. Please download the latest development version of the app to see how you like it. The interval widths DO NOT yet correspond to where the labels are positioned. I'll fix this if you're all sure this way of displaying the x-axis works for you.

**Comment by jessicagood** [comment]
Interval widths correspond correctly since commit 02d59d71608dcf8f1e4cf416b5afe19dc73abb87

**Comment by jessicagood** [comment]
@UASTeam You're good with this now right? Can we close this issue?

**Comment by UASTeam** [comment]
I'm happy with the x-axis as it is now. I'd be okay with closing this issue.
