### ISSUE TITLE
Update Ionic to beta 14

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#46]

**Comment by ginxwar** [comment]
issues:

1) transparency is gone in ion-nav-bar
2) $ionicViewService is deprecated (use $ionicHistory instead)

**Comment by jessica-azgs** [comment]
Updated with commit 187e22803ab0bb6521630f768eddcb989222ea4c. This also required fixing the view history (commit 215b78ea4c79ed3a405d750eb21db0da9f5dd17b), date/time input (commit d76830934d60aafbe9c8409c28c04586e5074871) and preventing a few of the pages from being cached - a new feature in beta 14 (commit 52c094999ba20d4e80446cb36de04996ffd1bfa2). Hopefully I caught all of the issues associated with the upgrade.
