### ISSUE TITLE
Sed: Structures Tab

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#461]
@UASTeam: In the latest version I added the Sed Structures tab. It only shows up if the Spot is a Strat Interval. If this is wrong and you want it to appear all the time or on a different condition let me know and I I can easily change it.

This is a really long form so see how it loads and if you're not happy with it it may need to be broken into sections.

Also, the following changes need to be made to the form:
- data column names need to be all lower case (not the field Labels)
- choice values need to be all lower case (not the choice Labels)
- choice values need to be 14 characters or less (not sure why KoBo forms does this but it is what it is)
- extra underscores should be removed
- names and values need to be looked-over so the they make sense
- use the Acknowledge question type, instead of a Select One, for fields that should just have a yes/no or true/false answer (like for the field Add physical structures)

**Comment by UASTeam** [comment]
I've split the form into 4 separate forms, so it will be like the sed lithologies form. Depending on the direction that we go with the "Strat Smart" will decide if I go through the forms to make the changes that you list.
