### ISSUE TITLE
Sed: Interpretations Tab

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#462]
@UASTeam: In the latest version I added the Sed Interpretations tab. Most of the comments I put in the [issue for the new Sed Structures tab](https://github.com/StraboSpot/strabo-mobile/issues/461) are applicable here too.

This tab only shows up if the Spot is a Strat Interval. If this is wrong and you want it to appear all the time or on a different condition let me know and I I can easily change it.

Also, the following changes need to be made to the form:
- data column names need to be all lower case (not the field Labels)
- choice values need to be all lower case (not the choice Labels)
- choice values need to be 14 characters or less (not sure why KoBo forms does this but it is what it is)
- extra underscores should be removed
- names and values need to be looked-over so the they make sense
- use the Acknowledge question type, instead of a Select One, for fields that should just have a yes/no or true/false answer

**Comment by UASTeam** [comment]
With the new interpretations subtabs are these still issues that need addressed?

**Comment by jessicagood** [comment]
Yes the bulleted items still apply and apply to all Sed forms. They just need to be cleaned up.

**Comment by UASTeam** [comment]
I've edited the xls files to resolve the above issues. Please review and let me know if I missed anything.

**Comment by jessicagood** [comment]
I found a few choice values where it still said option_19 or something similar and a couple that were more than 14 characters but I fixed these so I think it looks good now. I pulled the new forms into the code with commit c34ba0168111f549957598bcb21fc0e646c18892 and updated the development version of the app.
