### ISSUE TITLE
Text for magnetic declination in the Project description

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#463]
The current text is not clear enough.  Replace it with:

Enter declination based on whether magnetic north is east or west of geographic north.  If magnetic north is west, enter declination as a negative number; if it is east enter declination as a positive number.

**Comment by panamint55** [comment]
Better:


Enter declination based on whether magnetic north is east or west of geographic north. If magnetic north is west of geographic north, enter declination as a negative number; if it is east enter declination as a positive number.

**Comment by NathanNovak** [comment]
fixed with commit ad1ea713274cd515e9472b4a563fc4a567beb1e3
