### ISSUE TITLE
Sed: Need Interval Type in Basics Form

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#470]
@UASTeam We need the Interval Type field (that's in the Add Interval form) to also show up in the Basics form. Can you move it in there in the order you want it or let me know where you want it?

**Comment by UASTeam** [comment]
Added the Interval type just below interval thickness to the Basics subtab form.

**Comment by jessicagood** [comment]
@UASTeam There is a problem with the logic here. For example, you have Primary Lithology not visible until the bed or package field is answered. But the Primary Lithology might already be filled out from the Add Interval dialogue. Also, logic (matching the logic from the Add Interval dialogue) needs to be applied to Interval Type which you just moved in to this form too.

**Comment by UASTeam** [comment]
Logic issues fixed by getting rid of the interval type heading, and matching the add interval dialogue to the basics subtab with the 'is this a bed or package (succession of beds) or covered?'.
