### ISSUE TITLE
GPS Issue

### ISSUE THREAD

**Issue by UASTeam** [StraboSpot/strabo-mobile#472]
When used in the field, spot locations were either plotted 1) on top of each other for spots close by, or 2) miles away from where they should be. Error of this magnitude will make plotting the measured section path impossible. I did let the iPad sit with Strabo open for several minutes before updating spot location with no improvement in accuracy.

**Comment by jessicagood** [comment]
@UASTeam What type of iPad are you using? It is WiFi only or does it have a cellular radio as well? Apple doesn't put GPS receivers in the WiFi only iPads so the reading it gives isn't as good.

There's not much I can do about the accuracy of the GPS receiver. The app just records whatever number it receives from the device. But we can figure out how to make an external iPad GPS work if we need.

**Comment by jessicagood** [comment]
If rounding is one of the issues per @panamint55 I have the app set to round lat and long from getCurrentPosition() to 6 decimal places with commit 9fb8cd4e72719221d81e914418b825758ef4911f

**Comment by NathanNovak** [comment]
updated with commit c0aafce987eb94cb57221954295073593f040d8c
