### ISSUE TITLE
No appearance of interval

### ISSUE THREAD

**Issue by UASTeam** [StraboSpot/strabo-mobile#473]
When a new strat column is started, the first interval is not displayed unless you exit then reload the column. Additionally, if a second interval is added before reloading the column (to get it to display), it is plotted over the first (i.e. the first and second column share the same lower left coordinates). This requires deleting and re-adding the second interval in order for it to plot correctly.

**Comment by jessicagood** [comment]
Fixed with commit 4ad3d0c6230a41e01dd5949dcc0126a4a63bca80
