### ISSUE TITLE
Image origin in strat section needs to be able to be a negative number

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#475]
You can only set the lower left corner or an image overlay in a strat section to "0."  This need to be a negative number as well if the strat section starts somewhere in the image.

**Comment by jessicagood** [comment]
@panamint55 Do you have one of your video of this not working or more detail? I can set the "Image Origin X Value" (which is the lower left corner) to a negative number. Maybe calling it "Lower Left Corner X Value" instead of "Image Origin X Value" is better?

**Comment by panamint55** [comment]
On my android tablet there was no “-“ sign on the keyboard.  It only popped up numbers.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
***********************************************

**Comment by jessicagood** [comment]
My Android shows the following and works fine for that field. Which Android are you using? I'll need to figure out why some Androids don't show the "-" sign then.
![screenshot_20180416-111055](https://user-images.githubusercontent.com/1493985/38827287-4682023e-4167-11e8-9764-82667c07a3d7.png)

**Comment by jessicagood** [comment]
@panamint55 I've been reading about this issue with older Samsung keyboards and the solution many found was to install the Google keyboard.

**Comment by jessicagood** [comment]
Ok good. Closing this.
