### ISSUE TITLE
Sed: Selections not propagating into subsequent pages

### ISSUE THREAD

**Issue by UASTeam** [StraboSpot/strabo-mobile#482]
Relative resistance in the add interval dialogue isn’t propagating into the basics subpage.
Principal structures from the basics subpage are not propagating into the sed structures- physical subpage.

**Comment by jessicagood** [comment]
Fixed with commit 639e8b5e7ff20f3bd862dec9bc8d1bfa91ffb969
Fixed with commit 00b7fb333ff79349d6281a2868b0d5e7d909b257
