### ISSUE TITLE
Sed: Change color of section interval

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-mobile#483]
From sed field trip: There needs to be a way of controlling the color of the strat intervals. This could use the geologic unit Tag or be a separate color. Right now it appears to assign color based on lithology, but this was confusing when we added two shale-y layers that were adjacent.

**Comment by jessicagood** [comment]
Yes, the colors are set according to a list given to me by @UASTeam. See below. It looks like they are USGS set colors. If they're standard colors I wouldn't think we'd want to give the user the option to change the colors. Maybe once we add the patterns that would help differentiate similar intervals? @UASTeam what is your thought on this?

![image](https://user-images.githubusercontent.com/1493985/39258151-17ac1582-4868-11e8-8d03-d7de93b647e0.png)

**Comment by egbunse** [comment]
@jessicagood OK, I wasn't aware of how the color was chosen for this and I went back and checked my Strat Columns and the intervals appear to follow these colors. I wrote this based off a team on the field trip who asked me this question since they had two black adjacent intervals which made it hard to distinguish the two. I should have written down their lithologies for these intervals. Let's table this until @panamint55  or I work with the sed trip attendees on their Strat Sections to see if that was a mistake or bug. 
We should make a note to include this chart in the help section about the Strat Intervals. It may also be good to somehow incorporate this into Tag coloration.

**Comment by UASTeam** [comment]
The above list isn't standardized USGS colors, but rather a list that I put together simply based on lithology and approved (either explicitly or implicitly) by the other sed folks. I'm open to changing color options, though that is something that will need to be done before I make the color/pattern tiles for the column.

**Comment by jessicagood** [comment]
Colors updated by @UASTeam to:

![image](https://user-images.githubusercontent.com/1493985/39554038-6a235dee-4e25-11e8-83a8-03962ee24827.png)
