### ISSUE TITLE
Sed: 3D structures Validation Error for no selection

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/strabo-mobile#486]
Selecting "Adding a Fabric", "Adding a Tensor", or "Adding Other", then not making a selection, and closing out of the field in 3D structures page causes the a Validation Error modal to come up.  With this you are unable to navigate to other pages unless a required field is filled out.  There si a work around if you go into the "Add a Fold" section and then close out of there.

**Comment by jessicagood** [comment]
Fixed with commit 5512811d7eb3c4641f19d349712224db9457754e
