### ISSUE TITLE
Camera broken on iTunes version

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#489]
App version 1.1.0 crashes when taking a picture with iOS 11.3.1

**Comment by NathanNovak** [comment]
Jason,
I downloaded the app a couple different ways and the camera crashes the app only in a couple (listed below):
download developer version from PhoneGap  w/o Straabo on device previously- works fine
 1. download app directly from store w/o Strabo being on the device previously - crashes
2. download from store and installs over developer version - works fine
3. download Testflight version over developer version - works fine
4. download Testflight w/o Strabo (any version) on device - crashes

**Comment by NathanNovak** [comment]
I did not update the iOS to 11.3.1.

**Comment by jasonash** [comment]
I also updated the camera plugin to version 3.0.0 based on forum comments. It seems to work well.

**Comment by jasonash** [comment]
Fixed with 2c0bb3ac29df02dc8c8e5aed3f8f8e90a5a50f69
