### ISSUE TITLE
Automatic Login in Web Version No Longer Working

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#507]
Doug and I realized that automatic login is no longer working for the web version. When a user clicks on a project from strabospot.org, they are taken to the app to a random (or sometimes no) project selected. 

I rolled back through past commits and found that this error was introduced with commit aa237ac18cbc2008512df21d9198b2b6a14309ae where it looks like the autologin functionality has been commented out.

I moved the web version to the commit just prior to the commit above so that the web application will at least partially work.

**Comment by jessicagood** [comment]
Yes, the problem was simply that it was commented out. I need it commented out to work on it for development and forgot to uncomment it. @NathanNovak just took the commenting out of the master branch for me.

**Comment by jasonash** [comment]
@jessicagood and @NathanNovak OK, I pulled from master and everything seems to be working now. Thanks!
