### ISSUE TITLE
iPad keyboard split

### ISSUE THREAD

**Issue by aglazner** [StraboSpot/strabo-mobile#512]
I can’t split the keyboard either by pulling it apart or tapping and holding the keyboard icon
Using phonegap version 1.4.1

**Comment by NathanNovak** [comment]
Hi @aglazner ,
Are you using it on your IPad or on an IPhone?  Are you able to do it through another app?  How about with the AppStore version?

**Comment by NathanNovak** [comment]
@aglazner make sure the toggle for Split Keyboard in Settings --> General --> Keyboard is on.  I downloaded the latest PG version (1.5.0) on the IPad and was able to split, dock, and merge the keyboard.
What version of iOS are you running?

**Comment by aglazner** [comment]
iPad running latest iOS; toggle in settings was on. I will try it on 1.5.0 (how do I get it)?

On Aug 23, 2018, at 6:01 PM, Nathan Novak <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @aglazner<https://github.com/aglazner> ,
Are you using it on your IPad or on an IPhone? Are you able to do it through another app? How about with the AppStore version?

**Comment by jasonash** [comment]
I just verified that the keyboard split function works as expected on my iOS device (iPad) using both Strabo 1.4.1 from the App Store, as well as 1.5.0 from PhoneGap. My device is running the latest version of iOS (11.4.1).

@aglazner you can download 1.5.0 from PhoneGap here:
https://build.phonegap.com/apps/2865733/share

**Comment by NathanNovak** [comment]
I am going to close this issue for now.  @aglazner  if it keeps happening then we can start a new issue and go from there.
