### ISSUE TITLE
Show user if they are logged in or not

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#52]
Maybe disable the login button if already logged in and the logout button if already logged out? Or at least just write it somewhere.

**Comment by ginxwar** [comment]
If a user hasn't logged in, the menu will show "Login."  Otherwise logged in users as recorded by the LoginFactory will show the menu as "Logout XX"

**Comment by ginxwar** [comment]
see 44841bbd2fd6b28a58635ac36ef6f056b9b0653f

**Comment by jessica-azgs** [comment]
@ginxwar Sometimes the login fields don't show up when you open this page. But if you click on something else, like the sync up or down buttons, then the login fields appear. I think this might be because it has already rendered the page while it is waiting to get the response back from LoginFactory.getLogin(). I don't get this issue on the desktop but I do in iOS and Android.

Can you take a look at this? I tried a few things but could not get a successful fix.

**Comment by ginxwar** [comment]
See a6ff8122f936c6e1a279da6180de6d34b2488cc2.  LoginFactory is outside of Angular scope, so I had to wrap ```hideLoginButton()``` and ```hideLogoutButton()``` in ```$scope.$apply```
