### ISSUE TITLE
Strabo offline maps not downloading

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/strabo-mobile#524]
@jasonash I am testing the PG version with the changes made to the server and keep getting a message that says "zip download failed"  I tried at zoom 14 and 17.  

I tested this on an IPad with version iOS v12 running.

**Comment by jasonash** [comment]
OK, I'll take a look

**Comment by jasonash** [comment]
It looks like the file transfer plugin isn't working on Master. I'll see if I can fix this.

**Comment by jasonash** [comment]
@NathanNovak OK, try it again. It should be fixed now.

**Comment by NathanNovak** [comment]
@jasonash  everything looks to be working now.  I tested all the maps for offline and the biggest file was 4694 tiles which took less then 10 seconds to download so that was impressive.

**Comment by NathanNovak** [comment]
@jasonash  did you do a commit for the change?  I didn't see one in the list.

**Comment by jasonash** [comment]
@NathanNovak No, the problem was server-side. No change to strabo code necessary.

**Comment by NathanNovak** [comment]
ok I am going to close this then
