### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#527]
We should put the strabo icon on the main strabospot webpage somewhere.

https://strabospot.wordpress.com/

**Comment by jasonash** [comment]
I added the Strabo icon to the front page and header.

**Comment by panamint55** [comment]
thank

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************
