### ISSUE TITLE
Offline maps not showing up when placed in airplane mode.  

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/strabo-mobile#531]
when you save tiles for offline use then go into the map the page is blank with only the spots showing, but when you go out of the map and back in the offline maps reload.

**Comment by jasonash** [comment]
@NathanNovak I can't seem to duplicate this one. Are you using a version from PhoneGap?

**Comment by jasonash** [comment]
@NathanNovak I just did a fresh PhoneGap install on both of my devices (Android and iOS) and I don't see the behavior you describe above. Can you elaborate on what steps you took? What OS are you seeing this issue on? Can you make a video so we can see what is happening?

**Comment by NathanNovak** [comment]
@jasonash Here are the steps I took on an IPad running iOS 12:
1) From Main Map I downloaded the tiles for Topo for offline use and named a new map and set the zoom to max (19 in this case 1385 tiles...works great).  Every Baselayer is displayed as it should be too. 

2)I put the IPad in airplane mode and went back and Topo shows up. I switched over to a different offline map (Satellite) and there is nothing. Same goes with OSM.  I know I have offline maps downloaded.  

3) I get out of the maps and go to a different page (in this case Offline Maps) and select a map from there. Map shows up.  I get out of map again and all the offline maps are displaying.  

4) I turned airplane mode off then went back and everything is back to normal.  Then I went back to airplane mode on again and everything displays

**Comment by NathanNovak** [comment]
I tried to take a video with my phone (can't get the IPad on the Mac here and show) but have been having issues with the focusing on video mode.

**Comment by jasonash** [comment]
I'm updating to iOS 12 now. I'll see what happens.

**Comment by NathanNovak** [comment]
ok

**Comment by NathanNovak** [comment]
@jasonash I tested it on my Android phone and it works fine.  Then I deleted the PG version of the app and reinstalled it and now it works fine so maybe it was something about installing a PG version on top of a different PG version

Jess found the issue related (#492)

**Comment by jasonash** [comment]
@NathanNovak Yes, we've had issues with trying to install over old PG installs. I just tried a fresh install from PG on my updated (iOS12) device and it is working as expected.

**Comment by NathanNovak** [comment]
I did a fresh install and things seem to be working.  I am closing this issue

**Comment by panamint55** [comment]
v. 1.6 seems to work well for me.

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************
