### ISSUE TITLE
Mapbox Classic and Styles unable to be saved for offline use

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/strabo-mobile#533]
I pulled two basemaps from Mapbox (1 styles, 1 Classic) and I get the following message from each:

Mapbox Classic: "Invalid Map Specified"
MB Styles: "Invalid ID" 

both wouldn't download for offline use.  Each so show up in  Offline Maps with 0 tiles downloaded.

**Comment by jasonash** [comment]
@NathanNovak I just created three custom Mapbox styles and installed each as other basemaps in Strabo. I downloaded each successfully for offline use.

I will work on fixing the mapbox classic links.

**Comment by jasonash** [comment]
@NathanNovak Can you try downloading your Mapbox Style again? I can't seem to replicate this issue.

**Comment by NathanNovak** [comment]
I will try again with Styles

**Comment by jasonash** [comment]
@NathanNovak Can you provide me a map id and access token of a map that won't work? I can't seem to duplicate the problem.

**Comment by NathanNovak** [comment]
I am closing this issue because I tested and things are working with both Other Maps when importing and then downloading them for offline use.
