### ISSUE TITLE
Request: move disclosure triangles from far right margin to left where the user will notice them

### ISSUE THREAD

**Issue by aglazner** [StraboSpot/strabo-mobile#536]

**Comment by NathanNovak** [comment]
@aglazner I change the Select Map and the Zoom click area to span the entire length of the dropdown box.  If you want to back-up your data and do another Phone Gap install it is ready for you.

**Comment by NathanNovak** [comment]
fixed with commit 0315bd174b2be740f1b158cb49335d9333e74084
