### ISSUE TITLE
Extremely slow project upload

### ISSUE THREAD

**Issue by aglazner** [StraboSpot/strabo-mobile#540]
I set a project to upload last night. 4 spots and 19 iPad images. Woke up this morning and only 4 spots images had been uploaded; gear was spinning. Force-quit the app and tried again. Took 15 minutes or so to upload 15 images (4 failed, no message as to why or which images failed to upload). Wifi speed tests at 5 Mbps.

Export to device was quick and gave no errors.

**Comment by NathanNovak** [comment]
@aglazner just to outrule things do you know the size of the photos you were trying to upload? Was it from a drone or the IPad?  Was the 5 Mbps the upload speed or the download speed when you tested?  

While 5 Mbps is not incredibly fast if the files were quite large that may have played into the slow speeds and the failures.  

I appreciate you letting us know.

**Comment by aglazner** [comment]
These were Strabo-cropped and downsampled images, <1 Mb each.
