### ISSUE TITLE
Geologic unit slow load (and possible crash)

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/strabo-mobile#544]
@panamint55, 

We figured out what was causing the sluggishness with Geologic Units.  Back in April when there were changes to the Rock Unit forms to include select multiple it put a stress on the app when Geologic Unit is selected.  The amount of skip logic with select multiple combined with the number of choices (281 total) is creating the really slow response.  The best way to correct this is to split the Rock Unit survey and the Rock Unit Choices into 4 separate forms.

**Comment by panamint55** [comment]
OK, let’s talk about this next week.  Take a screen shot and show me what you are meaning.

Thanks.

Doug

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by NathanNovak** [comment]
@panamint55 I can take a screenshot of the code but it's really just the Kobo forms that should be split into four sections.

**Comment by NathanNovak** [comment]
@panamint55,

Found the issue and was able to fix the lag without separating the Rock Unit forms like we were talking about.  I will merge into master today.

**Comment by NathanNovak** [comment]
issue resolved . Closing issue
