### ISSUE TITLE
Reattaching image does not work

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#551]
Using 1.6.1 from newest phone gap build.  I cannot reattach a picture, even the one that was originally taken.  I get this error:

![image](https://user-images.githubusercontent.com/9283127/47889136-66ca9780-de16-11e8-8068-caee900f637a.png)

**Comment by NathanNovak** [comment]
@panamint55  can you try and replicate that again with the error catching from PG? 
Use this link:
https://build.phonegap.com/apps/3361635/share

**Comment by panamint55** [comment]
Done

Doug

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by NathanNovak** [comment]
@panamint55 have you received that same error message?  We combined the Sentry error catching and the master so if you want to download that version from PG and see if it is causing the same error.  I have not received an error on this end.  

https://build.phonegap.com/apps/2865733/share

**Comment by panamint55** [comment]
Use this link?  I am testing the other one but can switch back to this.

Doug

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by panamint55** [comment]
Still the same.  Just did it.

Doug

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by NathanNovak** [comment]
fixed with commit 4a6538fe87287f5461a4d8b3a2ad93b855053148

**Comment by NathanNovak** [comment]
@panamint55 reattaching images should work now.  I am going to close this ticket but if there are anymore issues regarding reattaching we can open a new one.
