### ISSUE TITLE
No line-specific attributes

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#56]
Currently, when select "linear" or "planar and linear", there is no change in the details for input.
A linear feature needs TREND and PLUNGE (instead of STRIKE and DIP).
A combination will need both sets of info.

There also needs to be types for linear features, and probably quality. Basically, the More Detail section should update to accommodate entering different attributes depending on which feature type is selected.

**Comment by jessica-azgs** [comment]
This all needs to be specified in KoBo Toolbox first. See issue #78
