### ISSUE TITLE
Tags Forms Freezing App

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-mobile#564]
For the past two days, the only Tag form that works (I can input data successfully) is the one that opens from the Spot form (Add/Remove Geologic Units). Going to the Tags Form from Spot tabs or from the hamburger menu displays my Tag list but nothing is clickable. So I can’t add tags from that form or edit existing ones in the list and need to restart the app since nothing (even the hamburger menu) is clickable. Primarily using a new iPad mini 4 but also tested the behavior on my Samsung Galaxy S7.

**Comment by NathanNovak** [comment]
Hi @egbunse what version of the app are you using (PhoneGap or AppStore version)?  Can you download the new Phone Gap version and recreate the issue?  Reason being that we installed an error tracking program that will alert us and give us very specific information about the code if there is an error.

**Comment by egbunse** [comment]
Hey, @NathanNovak, sorry about the omission. I am using the latest version in the app stores on both devices- 1.6.0. Could you direct me to the latest phone gap download site? The version I have for that is 1.0.0 from this spring. The iPad probably isn't on the UDID list so I'll just test on the Android phone.

**Comment by NathanNovak** [comment]
Hi @egbunse below is the link for the latest PG version:

https://build.phonegap.com/apps/2865733/share

Let me know if this fixes the issue. That version was working fine on the IPad here and the Android.  
Thanks!

**Comment by egbunse** [comment]
@NathanNovak Tags worked a lot better on the phone gap version on my Android. The only noticeable slowness was 'Show all geologic unit' but it was just a few seconds of loading.
