### ISSUE TITLE
Wish didn't have to delete initial "0"

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#57]
When user goes to enter info for Strike and Dip, there is an initial value of 0 that needs to be deleted each time. When it is empty, there is a message like "What is the strike?". It would be nice if it initialized with the message and if there was no need to delete something to enter a new value.

**Comment by ginxwar** [comment]
done.  See b189d022d8bbb109dc2abe92f4f38505ab53fecc
