### ISSUE TITLE
Photo upload

### ISSUE THREAD

**Issue by cashaw-mt** [StraboSpot/strabo-mobile#573]
Photos do not upload with project from mobile app to Strabo online. What is the procedure to upload photos while maintaining links to the spots where they belong?

**Comment by NathanNovak** [comment]
What version are you running? @cashaw-mt

**Comment by panamint55** [comment]
Did you get this fixed?  What version are you using?

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by cashaw-mt** [comment]
Hi Doug,
Thanks for the response. I’m using 1.7.8. I haven’t tried to upload pictures again since multiple failures last week. I’ll try again today. I’m back on campus now with relatively fast and reliable internet. I think my connection in Copenhagen last week was OK, but can’t really verify.

Cheers,
Colin

Colin A. Shaw
colin.shaw1@montana.edu<mailto:colin.shaw1@montana.edu>
406.994.6760

**Comment by panamint55** [comment]
Version 1.7.8 should work.  It may take a while, but it should eventually go with good internet.  Images are now huge, and can take a lot of time.

Doug


*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by jessicagood** [comment]
As of Sept 3 images are now downsized to a max of 2000 pixels for the larger of height or width on upload. Original resolution is still retained for the image on device. This will help with uploading when internet is slower.
