### ISSUE TITLE
minerals in pet-mineralogy tab disappearing

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/strabo-mobile#575]
I have found a bug where I will add minerals, go to the main Spot page for that spot, go back to the minerals page and there will be no minerals in it. It seems to happen when I create a new mineral, go from mineralogy to tertiary, add things in ternary,  go back to mineralogy, and then go to the spot tab. I get a blink of a blank mineralogy page before it goes to the spot page. This happens whether I add things to reactions or not.

**Comment by jessicagood** [comment]
@hannahcunning Was finally able to recreate it. Good find on this bug. Could you get the app again and see if the page still goes blank on you?
