### ISSUE TITLE
alteration,ore minerals being named "unknown

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/strabo-mobile#577]
under Pet Minerals->Mineralogy, When I choose a mineral from the Rock Class "Alteration, Ore" it makes the name of the mineral in the list "Unknown". This only happens when I choose the mineral from the list, and not when I enter the name or abbreviation for the mineral.

![Screenshot_20190822-151605_Strabo Mobile](https://user-images.githubusercontent.com/54119012/63546730-13821c80-c4f0-11e9-9ca0-a673aef0ac34.jpg)

![Screenshot_20190822-152321_Strabo Mobile](https://user-images.githubusercontent.com/54119012/63546927-89868380-c4f0-11e9-852e-9e9817b7314e.jpg)

**Comment by jessicagood** [comment]
Good catch! Just an extra 's' on the end messing it up. Fixed with commit 1260812658524cb6ea0baac9d0b99ea99eb6b990.
