### ISSUE TITLE
Layer Switcher icon (on iOS)

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#58]
A touch event on the layer switcher icon almost never registers on iOS.

**Comment by ginxwar** [comment]
I cannot reproduce this in safari on my ipad.  Layer switcher always open the layer suboptions when touching.  Touching on suboptions to switch layers and toggling geojson feature collections works great too.

**Comment by jessica-azgs** [comment]
I tried this from within the Web browser (strabo.usgin.org) and like you, don't seem to have the issue with it like I do when installing it natively though PhoneGap build. @zmichels Did you install the app through PhoneGap build? You have the only other iOS device which we have license to install the app natively on, correct? Are you encountering the problems I've described here or in the other issues I made yesterday? Wondering if there could be an issue with using PhoneGap Build to build the app.

**Comment by jessica-azgs** [comment]
I don't have this problem with the latest layer switcher button.
