### ISSUE TITLE
Downsample Images from App

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#580]
Change image quality to 75% and resize to 2000 pixels on long edge

**Comment by jasonash** [comment]
This might be of interest:

https://ionicframework.com/docs/native/image-resizer

**Comment by jessicagood** [comment]
I think we can do in right in the plugin options with `targetHeight` and `targetWidth`

https://github.com/apache/cordova-plugin-camera#cameracameraoptions--object

**Comment by jasonash** [comment]
Yes, but this would sacrifice the full-res version. If we capture at full-res and then resize after, the full-res version is retained in the camera roll. I think this is what Diane hinted at, to keep a good version on device for possible use later.

**Comment by jessicagood** [comment]
Tested this with commit a24db7b91c8e6b69755cebbf00ffd422d912e4fa. Android actually still keeps a full-res photo in the gallery but, as predicted, iOS does not.

**Comment by jessicagood** [comment]
Fixed with commit 64aa9b44b3409583155f60d16d3bf95e462d889b. Images resized to max height and width of 2000 on upload, when converting image to a blob.
