### ISSUE TITLE
Terms for petrology

### ISSUE THREAD

**Issue by aglazner** [StraboSpot/strabo-mobile#583]
Please:

Add the following to habit: anhedral, subhedral, euhedral

Add “seriate” to Plutonic Textures

Add “hydrothermal veins” to Modification

Make Modification panel show up on both plutonic and volcanic

**Comment by jessicagood** [comment]
@hannahcunning Can you add these when you make your other KoBo forms changes?

**Comment by hannahcunning** [comment]
Will do.
