### ISSUE TITLE
Duplicated mineral in Mineral GlossaryBUG REPORT 

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/strabo-mobile#590]
Hypersthene appears twice in the mineral glossary, as 'Hypersthene' and 'Orthopyroxene (Hypersthene)' . The entry under 'Hypersthene' can be removed.

**Comment by jessicagood** [comment]
@hannahcunning Sure, I can remove it from the glossary but I do see you use both `orthopyroxene` and `hypersthene` in the Minerals form.

**Comment by hannahcunning** [comment]
Orthopyroxene is a name for a group of minerals, and hypersthene is one of the minerals in that group.  

Also I forgot what I did for the mineral glossary. The entry with the name 'Orthopyroxene (hypersthene)' should be renamed to 'Orthopyroxene', and the entry under 'Hypersthene' should remain the same, as one refers to the group of minerals, and the other refers to the specific mineral.

**Comment by jessicagood** [comment]
Ok. Fixed with commit 79ea5422cf5f562dc91c2bc8c530033110c08e36 and PhoneGap build updated (but no new version number).
