### ISSUE TITLE
Web Version: Map hangs - BUG REPORT 

### ISSUE THREAD

**Issue by aglazner** [StraboSpot/strabo-mobile#591]
Repeated hangs when trying to access map from various directions (from a spot, by just trying to see the map, etc.), always with {{vm.something}}. See attached.
<img width="1206" alt="Untitled" src="https://user-images.githubusercontent.com/25137645/64719672-9eb25a80-d47d-11e9-9eec-855e719d888b.png">

**Comment by jessicagood** [comment]
@aglazner I don't have enough information to recreate this. Is is a problem with a specific Spot? What about in a different project? Do you still get the same issue?

**Comment by jessicagood** [comment]
The following was posted in a different issue and moved here.

From @aglazner: This is in the web app. Maybe I put the report in the wrong place. See attached link. It happens with different projects, and whether I get there from the Main Map menu item or click the folded map in a spot description.

https://www.dropbox.com/s/q3g1o5s8pshwgy2/Hang.mov?dl=0

**Comment by jasonash** [comment]
@jessicagood I tried upgrading the web version to 1.9.0, but there are still issues with the map sidebar that are causing the app to hang. See this video:

https://www.dropbox.com/s/imgnpsaw0znjkgj/1.9.0.Map_Sidebar_Error.mov?dl=0

I put version 1.8.5 back up, but it also has issues with the map sidebar: 

<img width="759" alt="Screenshot 2019-09-13 13 28 37" src="https://user-images.githubusercontent.com/7904402/64886085-02c65180-d62b-11e9-8f61-65d3c17639ef.png">

**Comment by jessicagood** [comment]
When I added the Notes page I didn't add the content of the page to map side panel in the web version. I've added it now with commit f5d58ab902500cb1007cb7bfacc6c83ff302e5c8. Could you see if it works?

Oddly I wasn't getting any errors or hanging, just no content in the Notes in the side panel. Even when I logged into the GSA project.

Obviously no need to update the mobile app since this was only effecting the web version.

**Comment by jasonash** [comment]
@jessicagood OK, I made 1.9.1 live on the server. It looks like it is working correctly now. Thanks for the quick fix.
