### ISSUE TITLE
Unable to import maps (or use any scroll menu) on iPhoneX

### ISSUE THREAD

**Issue by mikeastearns** [StraboSpot/strabo-mobile#593]
**Describe the bug**
When accessing any feature that has a scrolling, such as adding a map from 'Other Basemaps', you cannot choose an option. The scroll wheel works, but touching/choosing one option doesn't do anything.

A related issue is that this same operation crashes the web-based version.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to 'Other Basemaps' page
2. Click on 'plus icon'
3. Click/select the 'Select Map Type'
4. A scroll menu appears
5. See error

I have a screen recording, but I cannot upload.

 - iPhone X
 - OS: currently 13, but this error occurred in 12 too.
 - StraboSpot Version most recent

**Comment by NathanNovak** [comment]
@mikeastearns I loaded the app on an IPhone X simulator and I see what you are talking about.  after doing some research, the technology we use to run the app doesn't supply a "done" button on the iOS picker.  To make a highlighted selection you need to touch the "Map Type" dropdown box.  This is only an issue on IPhones.  IPads bring up a separate selection modal that allows the user to select an option within the modal.  

We are currently working on a second version of the app where the user interface will be more friendly and intuitive.  Let me know if you have any questions.  I am going to close this issue for now.
