### ISSUE TITLE
Need to keep spot label by station

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#608]
Per Basil:
Need to keep spot label by station, even if it has dip amount.  That is, show strike and dip symbol, but don’t show the dip amount.  Rather, keep station identifier by it. 

Per Doug, this should be for ONLINE version only.

**Comment by jessicagood** [comment]
Fixed with commit addd2d480fe44d2d9f1d470ff2fd5239d6f16f25
