### ISSUE TITLE
Notes on Desktop Version Broken

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#609]
According to Basil:

For notes entered in the desktop.  The text in notes has every word capitalized and run together.  This is not the case (as far as I know) for text entered in the app.

**Comment by jessicagood** [comment]
@btikoff Is this on the main Notes page? I can't recreate the issue. Did anyone else have this issue or know how to recreate it?

**Comment by alexanderlusk** [comment]
@jessicagood  if Basil makes a station with any formatting (e.g. new paragraph) and I then go and look at the station in strabo search, the formatting doesn't show up for me and Each Word Is Capitalized. I can send a screen shot of what I see, if that would help.

**Comment by jessicagood** [comment]
Yeah, screenshots would really help. You can paste right in your comment. When you say strabo search do you mean https://strabospot.org/search/? Do the words look correct in the app?

**Comment by alexanderlusk** [comment]
<img width="894" alt="Screen Shot 2020-04-03 at 2 59 37 PM" src="https://user-images.githubusercontent.com/25871635/80405599-af320c80-8877-11ea-9afc-3958961d2811.png">
I can't speak for the app. Can I access Basil's points on my app?

**Comment by alexanderlusk** [comment]
<img width="1146" alt="Screen Shot 2020-04-27 at 11 09 30 AM" src="https://user-images.githubusercontent.com/25871635/80406146-73e40d80-8878-11ea-9089-12cdcb7ac616.png">
I don't know about the app. Can I access Basil's saved spots on the app version?

**Comment by jessicagood** [comment]
You'd have to have his user name and pw to access it. It'd be helpful to know how it looks through the app, either on the device or web.

**Comment by alexanderlusk** [comment]
Ah, ok. I believe when Basil looks at it on his account it looks correct... regardless of desktop/app.
@btikoff can you confirm?

**Comment by jasonash** [comment]
@alexanderlusk This should be fixed now. Please take a look and let me know if your notes appear as expected now.
