### ISSUE TITLE
Tapping on spot doesn't reliably open popup (on iOS)

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#61]
This doesn't work about half the time.

**Comment by ginxwar** [comment]
I'm on an iPad mini 2 ios version 8.1.3.  My mobile safari useragent string is:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

Launching the app from http://services.azgs.az.gov/, I can get the spot popup more than 75-80% of the time.  I trick I use is tap in the middle of the spot (point) where it is the thickest so your margin of error is lower.  In other words, tap near the spot where the rectangle is joined up next to the line.

![image](https://cloud.githubusercontent.com/assets/1930629/5971720/b6071bfc-a800-11e4-9ffe-6539a156ee80.png)

Can you try this and let me know if this works better?
