### ISSUE TITLE
Add Public URL to Image Detail

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#611]
Per Basil:

Instructors will want to make sure of photos or sketches entered into STraboSpot, but can’t access them.  Please have a pointer to the URL of the picture (photo, sketch), so they can go get them.

URL would look like:

https://strabospot.org/pi/15851589624125

**Comment by jessicagood** [comment]
Added with commit 27f3f468487230906e30ad76350c9e8c82b17e60
