### ISSUE TITLE
Toggle spot symbology

### ISSUE THREAD

**Issue by alexanderlusk** [StraboSpot/strabo-mobile#614]
@jessicagood For using strabo as a teaching tool, it would be useful to be able to toggle the spot strike/dip symbols on an off (on an image basemap or the main map) and have them replaced by just a point (i.e. no symbology). How difficult would this be?

**Comment by jessicagood** [comment]
This wouldn't be too difficult but the student could just go ahead and toggle the symbology back on.Is this something I should work on in SS1 @panamint55?

**Comment by jessicagood** [comment]
Added with commit ea05f56cc213012d8fd762d9dd37de0de821ae75
