### ISSUE TITLE
BUG REPORT: spots in image basemap offset in "search" vs "desktop"

### ISSUE THREAD

**Issue by alexanderlusk** [StraboSpot/strabo-mobile#616]
**Describe the bug**
Spots (orientations, etc) do not appear in the same place on an image basemap in online search vs the desktop app.
Images below:
![Screen Shot 2020-05-07 at 2 05 27 PM](https://user-images.githubusercontent.com/25871635/81345250-f933a300-906c-11ea-852a-43ce2e18e0d9.png)
![Screen Shot 2020-05-07 at 2 05 04 PM](https://user-images.githubusercontent.com/25871635/81345261-fcc72a00-906c-11ea-950d-a9450423a34e.png)

**Comment by jasonash** [comment]
This appears to be a bug on the search interface. I will look into it.

**Comment by jasonash** [comment]
@alexanderlusk OK, this issue should be fixed now. Please have another look.

**Comment by jasonash** [comment]
Fixed.
