### ISSUE TITLE
Spot Symbol not changing with addition of planar strike and dip

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#617]
From Casey Buchanan via Gmail:

I recently downloaded StraboSpot on my phone (iPhone 7) and it seems to work fine for the most part, but I noticed that when I add a strike and dip to a planar feature it doesn’t change the generic black dot symbol to a strike and dip symbol. Is there a setting that a need to turn on first or should it automatically update the symbol. Note it does show the dip in degrees next to the dot.

**Comment by panamint55** [comment]
You have to make sure you classify the planar feature type.  It remains a dot until you do this.  Otherwise, it does not know what symbol to use.

Doug
