### ISSUE TITLE
BUG REPORT 

### ISSUE THREAD

**Issue by ThomasMGeo** [StraboSpot/strabo-mobile#622]
**Describe the bug**
Looking at the PDF help, I want/need to export the spots as a csv

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Open app
2. go to project
3. click on spots
4. click on dot icon in the upper right

**Expected behavior**

**Screenshots**
![IMG_5688](https://user-images.githubusercontent.com/38228140/96679179-5f1c9a00-1330-11eb-8dc1-79e3c29e69a5.jpg)

**Smartphone (please complete the following information):**
 - iphone 8
 - OS: [e.g. iOS13.6.1]

**Additional context**

**Comment by jasonash** [comment]
Hi Thomas. Unfortunately, the CSV export option for StraboSpot V1 has been deprecated and removed. We are currently developing StraboSpot V2 and this feature should be included that release.

In the interim, you can still download your data as XLSX by doing the following:

1. Upload your project to the StraboSpot.org database via Project -> Manage -> Three dot menu -> Upload Project
2. Go to StraboSpot.org and login to your account
3. Under Account -> My Data, choose your preferred download option:

<img width="507" alt="Screen Shot 2020-10-21 at 11 58 41 AM" src="https://user-images.githubusercontent.com/7904402/96753790-f7009f00-1395-11eb-9449-e8564315cafc.png">

I hope this helps. Please let us know if you have any further questions.

Thanks,

Jason

**Comment by ThomasMGeo** [comment]
Hi Jason,

Thanks! I was scared that it was stuck forever.

Thanks,
Thomas
