### ISSUE TITLE
BUG REPORT 

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#625]
The following was reported via strabospot@gmail.com:
Hi,

If I try to enter a start or end date for a project in the Basic Info window under the Description menu, the date always resets to mm/dd/yyyy once I attempt to enter the third number. I don't think I am doing anything wrong. Btw, this problem occurs using the web version. I'm using a PC, which I doubt matters anyway. I'm not sure if you can enter this information with the mobile app. Anyway, it's kind of an annoying and it would be nice to get that bug fixed.

Thanks for your help,

Jochen

I can confirm that both the web application and mobile application do not accept any input on start date or end data.

**Comment by jessicagood** [comment]
Fixed with commit 518b253
