### ISSUE TITLE
Need a way to *relate* entries

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#68]
User needs to be able to add relationships between data.
For example:
• Combine multiple data points to define a new SPOT
• Add a relationship between data that can communicate  something like:
    "X group of measurements are fault surfaces that cross-cut faults in Y group."

**Comment by ginxwar** [comment]
@zmichels could you take a look at the GeoJSON spec at http://geojson.org/geojson-spec.html?  I'm wondering if the GeoJSON spec would be sufficient to handle the type of relationships you're describing.

Short version of the spec: The smallest unit in GeoJSON is a Feature, which is either a point, line, or polygon; each feature can have any number or self-supplied properties.  A collection of Features (points, lines, polygons) can be grouped into something call a FeatureCollection.  You can create a FeatureCollection of any arbitrary size Features, and describe properties about the FeatureCollection as a whole.

Visually speaking, is a "SPOT" either a point, line, or polygon?

**Comment by zmichels** [comment]
Kevin,

My limited understanding is that this seems like it can handle grouping features adequately. I can’t tell how it handles (if at all) making subsequent groups of preexisting-groups, or if it is any problem to make multiple groups of different kinds that have overlap in their members (of features or feature groups). The backend for the data are (as I understand) being handled by a graph database structure so that we can have complex relationships between different observations and collections of data. 
The notion of a spot is that it communicates some information that is applicable over some related region of space. In this regard, a spot (which is any singular or group of observations or interpretations) is tied to a geographic reality… but itself does not need to define a specific shape (point, line, polygon). A spot should be able to be a collection of features that have geometries that are different from one another (e.g., a spot that contains lines and points, for which the relationship might be that they are all features within a given shear zone).

Z

**Comment by smrazgs** [comment]
A spot is located by a point,line or poly.  The geometry establishes geospatial context.

Since geoJSon is json we should be able to add any properties we need

Sent from my HTC on T-Mobile 4G LTE

----- Reply message -----

**Comment by smrazgs** [comment]
Each spot needs to have a unique identifier, ideally an http URI that we can dereference using the WWW. We could use local ID's that could be prefixed to get the HTTP URI

Sent from my HTC on T-Mobile 4G LTE

----- Reply message -----

**Comment by smrazgs** [comment]
@jessica-azgs hasn't this been handled?
