### ISSUE TITLE
provide visual indicators to the user during the upload/download data sync

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#72]

**Comment by ginxwar** [comment]
upload spot progress now shown to user.  See 5b76143c5857fd4e23e07f5963d6f65c5810d5ef

Not sure if we need a download progress because the download comes as one payload, not multiple

**Comment by ginxwar** [comment]
added alert message to user concluding the upload/download process.  Could easily be refactored to a better visual indicator instead of a blocking alert message.  But this is dependent on whether we want a single button to data sync or separate upload/download buttons.

**Comment by jessicagood** [comment]
Good indicators now abffa474839ccec9d2fc794d7b710b048d940c15
