### ISSUE TITLE
layer switcher should be part of the draw control group 

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#73]
the layer switcher should be the "4th" box.  We also need to make the layer switcher look/feel like leaflet draw layer switcher controls.

**Comment by ginxwar** [comment]
see b7af291a8ce7c2747ca9040e0cc996be9710f2f6

**Comment by jessica-azgs** [comment]
These new buttons look a million times better @ginxwar. Great job!

**Comment by ginxwar** [comment]
Cool!  Once I figured out to do this its pretty easy to change styles if we
need to later
