### ISSUE TITLE
submenus hold state and does not "reload" when changing to a different submenu

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#74]
The offline tiles submenu loads when you first visit the page but future visits to this page does not trigger a "reload".

Looks like bug/feature introduced in ionic beta 14.  I can confirm that this does behavior did not occur prior to the beta 14 commit

**Comment by jessica-azgs** [comment]
beta 14 caches views ... see the fixes I made in this commit 52c094999ba20d4e80446cb36de04996ffd1bfa2 ... you'll probably have to just turn off caching for that page

**Comment by ginxwar** [comment]
ah, that's it.
