### ISSUE TITLE
android app doesn't run anymore

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#87]
i get a message saying the app has stopped when i try to run the app. it worked before my latest download. Are we still on version Strabo Mobile 0.0.1?

**Comment by jessica-azgs** [comment]
@JEAndrew could you give us more detail on what device you're running and what version of Android? The latest version on Android works for us.

**Comment by JEAndrew** [comment]
It worked yesterday morning and then I updated  from the Web and it wouldn't run, then last night I downloaded and now it works.  I have a brand new Samsung galaxy 5s with relatively recent software, I'm fully updating it now.  Thanks,  I'll let you know if there are more problems. The app is already much better than I thought we could get,  but everyone wants a perfect app.


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by ginxwar** [comment]
Closing this issue for now.
