### ISSUE TITLE
display user location on map

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#89]
once geolocated, the display should show:

1) dot
2) north arrow direction?

**Comment by jessica-azgs** [comment]
pulsing circles

**Comment by ginxwar** [comment]
See commit 71cbf99c6fd142030f813dbcaf52bf546cb4aa50.  I added:

* geolocated center visual indicator
* heading indicator
* error tolerance in meters
* speed in meters per second

Outstanding issues:
* failed geolocation should result in a different visual indicator or stalled visual indicator
* altitude?
* pulsing circles require animated PNG or animated SVG?
* map center to move as geolocation position constantly updates?

**Comment by jessica-azgs** [comment]
- With failed geolocation the user should be alerted and then no visual indicator shown
- The ripple http://ionicframework.com/docs/api/directive/ionSpinner/
 would look nice if we were to animate it.
- Need a way to hide the indicator in case you don't want to see it anymore. Maybe the geolocate button should be a toggle instead and when it is on the indicator is shown and follows the user and when it is toggled off the indicator is removed from the map?

**Comment by ginxwar** [comment]
geolocation can now be turned off in 72da94616986f2201711e9530613050701332e38

**Comment by ginxwar** [comment]
The ripple is SVG and I'm unsure how to incorporate it at the moment.  Going to backburner this issue.
