### ISSUE TITLE
Add pictures to Spot

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#9]
Add ability to add pictures, taken with phone camera or added from file, to a Spot.

**Comment by ginxwar** [comment]
see commit 76e517e94599df39984c86c6adca00c95f0db266

**Comment by jessica-azgs** [comment]
Great! Works on my Droid Mini. Needs more testing, especially on the ipad, once we get the license certificate, before closing so I am reopening. I also don't see how you add a picture from file.

**Comment by jessica-azgs** [comment]
Clicking the camera icon should give you the choice to take a picture or attach a picture from your gallery (from file).

**Comment by ginxwar** [comment]
done.  See commit 2c5a3e74c20d3d97e0a857908e5a2ccbc7172f26

**Comment by jessica-azgs** [comment]
Great! Works to add a picture from file on my Android. The Photo Library and Saved Photo Album give me the same thing though. How are they supposed to be different? If they're even slightly similar just giving the user the 2 options of the Photo Library and the Camera would be less confusing.

**Comment by jessica-azgs** [comment]
Can't test it on iOS until we get the license certificate since the camera feature will only work when running the app natively. @ginxwar Feel free to close this issue again after you've addressed the last comment. We can assume it will work on iOS for now and make a new issue if this appears to be a problem.

**Comment by zmichels** [comment]
FYI: Keep getting an Out-Of-Office reply from Dave (the guy fixing together our provisioning license stuff). Says he’ll be back on 23rd… Now that we have the UDID’s, I am anticipating that he should be able to get us up and running shortly after his return. I will keep you posted.

**Comment by ginxwar** [comment]
Here's the doc for camera source type:  http://docs.phonegap.com/en/edge/cordova_camera_camera.md.html.

Camera.PictureSourceType = {
    PHOTOLIBRARY : 0,
    CAMERA : 1,
    SAVEDPHOTOALBUM : 2
};

The PHOTOLIBRARY is the entire photo library and the SAVEDPHOTOALBUM is suppose to be just the saved photos (subset of the entire library?)

I'm not 100% sure because on my Nexus 4, both appear to be the same.  Maybe we can test this out in iOS and see if it'll bring up something different?  Could be that it's OS specific.
