### ISSUE TITLE
zooms beyond 18/19 should continue to zoom

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#90]
we should have the ability to zoom in "infinite" mode.  Zooms with no actual tiles should then "zoom" in on the image, making the image "blurry."  This is better than zooming into a tile that doesn't exist.

May require investigation in to map providers min/max zoom bounds.

**Comment by ginxwar** [comment]
I can't really reproduce this problem so I ended up adding a zoom informational control to the lower left corner on the map tile screen so that the user can tell what zoom level they are at.

This is also helpful if you've accidentally zoomed in too far and you dont have a reference point to gauge the location or that you might think you've lost your internet connection.  Having the zoom informational control will at least show you that you've zoomed in too far.

**Comment by jessica-azgs** [comment]
see issue #187
