### ISSUE TITLE
different spot types have different symbology

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-mobile#91]
A point could have more than one symbology per "point."  In other words, there could be a strike/dip AND a trend/plunge.

Whatever symbol/image we come up with for trend/plunge, we should explore how transposing two images together could affect the display interface.

**Comment by jessica-azgs** [comment]
**Orientation Spots**
*All orientation spots have either a strike/dip or trend/plunge. Just using one symbol for all different orientation feature types for now*
- strike/dip symbol
- trend/plunge symbol

**Spot Groups**
*Don't symbolize in map if feature collection layer is on but do symbolize if group layer is turned on*
- dot

@zmichels What other symbols for the other content models? Can also use a label next to the symbol, right now the label is pulled from name.

**Comment by ginxwar** [comment]
@zmichels when you are ready to export the Illustrator files for the different symbologies, lets try exporting SVG as well as PNG.  I'm not sure which format would work better, so lets get both if it's not too difficult.

**Comment by zmichels** [comment]
Sounds good. Probably won't happen until Monday, but not a problem.

**Comment by zmichels** [comment]
I posted a .zip with some map symbols in both formats here:
https://www.dropbox.com/s/p4kvmoe9rdacw37/strabo%20map%20icons.zip?dl=0

**Comment by ginxwar** [comment]
@zmichels these are nice!  I'll get working on incorporating this in our project.

**Comment by ginxwar** [comment]
@zmichels I noticed that most of these images (assuming orientation feature types) have either an "inclined" or "vertical" property.  For example:

* contact_inclined
* contact_vertical
* cleavage_inclined
* cleavage_vertical
* fault_surface_inclined
* fault_surface_vertical

What should I look for in determining whether the point icon displayed on the map is inclined or vertical?  I didn't see this as an option in the kobo forms.

**Comment by zmichels** [comment]
The inclined ones will be most used and are for measurements with dip or plunge > 0 and < 90. The horizontal ones are for special cases where dip or plunge = 0. Vertical ones are for dip or plunge = 90. 
If it is too difficult to add special cases like this, then just proceed with the inclined version for all measurements.

**Comment by ginxwar** [comment]
initial commit for this has been done  I also added a spot group custom image to identify a "spot group"

**Comment by ginxwar** [comment]
@zmichels in 4b500d2b93da255e02415312d5db20aaf7d326f7, I updated the symbology based on our email conversation.  For now, all the content models are defaulting to the "_inclined" versions of the graphics you've generated.  Could you take a look and see if this satisfied requirements?

**Comment by ginxwar** [comment]
Symbology is broken again due to the change of the spot type.

Can we crosswalk the following types to an appropriate symbology?

###### Points
* Measurements and Observations
* Spot Grouping

###### Lines
* Contacts and Traces
* Spot Grouping

###### Polygon
* Polygon Form
* Spot Grouping

### The symbologies are:

* bedding_horizontal
* bedding_inclined
* bedding_vertical
* cleavage_inclined
* cleavage_vertical
* contact_inclined
* contact_NO_ORIENTATION
* contact_vertical
* fault_location_NO_ORIENTATION
* fault_surface_inclined
* fault_surface_vertical
* fold_axis
* fold_NO_ORIENTATION
* foliation_general_inclined
* foliation_general_vertical
* foliation_horizontal
* joint_surface_inclined
* joint_surface_vertical
* lineation_general
* MISC_note_or_description
* sample_locality
* shear_zone_inclined
* shear_zone_vertical
* striation

**Comment by ginxwar** [comment]
symbology logic updated to reflect latest spot type changes in 49fbb3b161f3d9a19bdb489ce40c246d011ab131.

@zmichels, We are still missing the following image types:
* axial plane surface
* fracture
* vein
* shear fracture
* other
* (blank)

Also, does EVERY image have a rotational aspect to them?  In other words, every "point" has a strike/dip, so should every image rotate according to their strike/dip degrees?

**Comment by zmichels** [comment]
Yes, they should all rotate.
For now, for these that are "missing", let's use the same symbol that we have designated for a dipping foliation. My biggest concern at the moment is that line measurements (at point locations) are being plotted with a symbol used to communicate a planar feature... So I'd be happy if we could just get our symbols coordinated enough that we can display arrows for linear features.

**Comment by JEAndrew** [comment]
For now we can use the symbols you have for these missing types:
Axial plane surface = symbol for cleavage
fracture and shear fracture = symbol for fault (maybe different colors of same symbol?)
vein = symbol for joint (ideally the joint symbol should have an open box and the vein a filled box)
other = maybe bedding with a "?" or possibly as a different color?
blank = a dot

**Comment by jessica-azgs** [comment]
@zmichels or @JEAndrew Can you check the chart below to see if this is what you want and edit accordingly? This is based only on the images I have already in https://github.com/StraboSpot/strabo-mobile/tree/master/assets so if there is a different png you want to use or a new one to add please email that to me. Also, which symbol do we use if there is both a planar_feature_type and a linear_feature_type?

Icons used if there is a planar_feature_type:

| planar_feature_type  | dip | file |
|:---|:---|:---|
| bedding  | 0  |  bedding_horizontal.png |
| bedding  | 0 < dip < 90  | bedding_inclined.png  |
| bedding  | 90  | bedding_vertical.png |
| contact  | 0  | default (point.png)  |
| contact  | 0 < dip < 90  | contact_inclined.png  |
| contact  | 90  |  contact_vertical.png |
| foliation  | 0  | foliation_horizontal.png  |
| foliation  | 0 < dip < 90  | foliation_general_inclined.png  |
| foliation  | 90  |  foliation_general_vertical.png |
| axial_planar  | 0  | default (point.png)  |
| axial_planar  | 0 < dip < 90  | cleavage_inclined.png  |
| axial_planar  | 90  |  cleavage_vertical.png |
| fracture  | 0  | fault_location_NO_ORIENTATION.png |
| fracture  | 0 < dip < 90  | fault_surface_inclined.png  |
| fracture  | 90  |  fault_surface_vertical.png |
| joint  | 0  | default (point.png) |
| joint  | 0 < dip < 90  | joint_surface_inclined.png  |
| joint  | 90  |  joint_surface_vertical.png |
| fault_plane  | 0  | fault_location_NO_ORIENTATION.png |
| fault_plane  | 0 < dip < 90  | fault_surface_inclined.png  |
| fault_plane  | 90  |  fault_surface_vertical.png |
| shear_fracture  | 0  | fault_location_NO_ORIENTATION.png |
| shear_fracture  | 0 < dip < 90  | fault_surface_inclined.png  |
| shear_fracture  | 90  |  fault_surface_vertical.png |
| shear_zone  | 0  | default (point.png) |
| shear_zone  | 0 < dip < 90  | shear_zone_inclined.png  |
| shear_zone  | 90  |  shear_zone_vertical.png |
| other  | any  | default (point.png) |
| vein  | 0  | default (point.png) |
| vein  | 0 < dip < 90  | joint_surface_inclined.png  |
| vein  | 90  |  joint_surface_vertical.png |

*All symbols rotate on the strike

Icons used if there is a linear_feature_type:

| linear_feature_type  | plunge | file |
|:---|:---|:---|
| fault  | 0  | fault_location_NO_ORIENTATION.png |
| fault  | 0 < plunge < 90  | fault_surface_inclined.png  |
| fault  | 90  |  fault_surface_vertical.png |
| solid-state  | 0  | default (point.png) |
| solid-state  | 0 < plunge < 90  | default (point.png)  |
| solid-state | 90  |  default (point.png) |
| fold hinge  | 0  | fold_NO_ORIENTATION.png |
| fold hinge  | 0 < plunge < 90  | fold_axis.png  |
| fold hinge | 90  |  default (point.png) |
| intersection  | 0  | default (point.png) |
| intersection  | 0 < plunge < 90  | default (point.png)  |
| intersection | 90  |  default (point.png) |
| flow  | 0  | default (point.png) |
| flow  | 0 < plunge < 90  | default (point.png)  |
| flow | 90  |  default (point.png) |
| vector  | 0  | default (point.png) |
| vector  | 0 < plunge < 90  | default (point.png)  |
| vector | 90  |  default (point.png) |
| other  | 0  | default (point.png) |
| other  | 0 < plunge < 90  | default (point.png)  |
| other | 90  |  default (point.png) |

*All symbols rotate on the trend

**Comment by jessica-azgs** [comment]
Images are actually in https://github.com/StraboSpot/strabo-mobile/tree/master/www/img/geology

**Comment by jessica-azgs** [comment]
I've modified the table above since I first wrote that comment. I've also changed the symbology in the app and pulled that into phonegap build and strabo.usgin.org. Check the About page to make sure you're at Version 0.4.1 - July 8th, 2015. The symbols should be easy to change once I know more precisely how you want the symbols and have the icon png files. But at the very least, lineations are now showing up with their own symbols.

**Comment by JEAndrew** [comment]
This is great progress. I have a few modifications:
(1) Is there a way to overlap the planar and linear symbols for stations with both types of measurements?
(2) Is there a way to change the placement of the dip and plunge number? The dip value should be at a position 90 degrees from its current location, placed in the location outward from the hatch mark on the planar symbol.  The plunge value needs to be placed a little bit farther out because right now it overlaps the arrow on the linear symbol.
(3) a few of the symbols are not correct. I will sort through them and try to find new symbols for you in a subsequent post.

**Comment by JEAndrew** [comment]
Does Strabo need png or svg files for symbols? where are these symbols from?

**Comment by JEAndrew** [comment]
The fold lineation symbol should be a red-pink color.

**Comment by jessica-azgs** [comment]
You're first few questions will need some research. I don't think either of them are easy to implement.

These files were given to us by @zmichels. I don't know where he got them from. The app is using the png files. I still need to go through and remove the ones we're not using and the svg files. All the symbols need to have about the same pixel dimensions so check that out too before giving us new pngs.

**Comment by JEAndrew** [comment]
How do I add my new png symbol files to the repository?

**Comment by jessica-azgs** [comment]
You can just email to me and Kevin.

**Comment by JEAndrew** [comment]
Last week or so I emailed several new png files for symbols to Jessica (I don't have Kevin's email). Below I outline the usage of the symbols.

planar_feature_type	dip	file
bedding	0	bedding_horizontal.png
bedding	1-89	bedding_inclined.png
bedding	90	bedding_vertical.png
contact	0	contact_inclined.png
contact	1-89	contact_inclined.png
contact	90	contact_vertical.png
foliation	0	foliation_horizontal.png
foliation	1-89	foliation_general_inclined.png
foliation	90	foliation_general_vertical.png
axial_planar	0	cleavage_inclined.png
axial_planar	1-89	cleavage_inclined.png
axial_planar	90	cleavage_vertical.png
fracture	0	fracture.png
fracture	1-89	fracture.png
fracture	90	fracture.png
joint	0	joint_surface_inclined.png
joint	1-89	joint_surface_inclined.png
joint	90	joint_surface_vertical.png
fault_plane	0	fault.png
fault_plane	1-89	fault.png
fault_plane	90	fault.png
shear_fracture	0	shearfracture.png
shear_fracture	1-89	shearfracture.png
shear_fracture	90	shearfracture.png
shear_zone	0	shear_zone_inclined.png
shear_zone	1-89	shear_zone_inclined.png
shear_zone	90	shear_zone_vertical.png
other	any	default (point.png)
vein	0	vein.png
vein	1-89	vein.png
vein	90	vein.png


linear_feature_type  file
fault striation		striation2.png
solid_state		solidstateline.png
fold_hinge		fold_axis.png
intersection		intersectionline.png
flow		                flowline.png
vector		        vectorline.png
other		        lineation_general.png

**Comment by JEAndrew** [comment]
![vectorline](https://cloud.githubusercontent.com/assets/11632667/8911600/28c65b06-3453-11e5-9f28-c4390ffb9ca3.png)

**Comment by JEAndrew** [comment]
fault.png
![fault](https://cloud.githubusercontent.com/assets/11632667/8911616/42454312-3453-11e5-8f75-94d380343604.png)

**Comment by JEAndrew** [comment]
fracture2.png
![fracture2](https://cloud.githubusercontent.com/assets/11632667/8911624/5045b58c-3453-11e5-90f8-4a4e5c529b21.png)

**Comment by JEAndrew** [comment]
shearfracture.png
![shearfracture](https://cloud.githubusercontent.com/assets/11632667/8911636/6052044e-3453-11e5-92d9-48a6f8c2c5ed.png)

**Comment by JEAndrew** [comment]
vein.png
![vein](https://cloud.githubusercontent.com/assets/11632667/8911645/6bb79c18-3453-11e5-8572-fe9525bd643e.png)

**Comment by JEAndrew** [comment]
flowline.png
![flowline](https://cloud.githubusercontent.com/assets/11632667/8911647/74474c02-3453-11e5-8233-b4a87ed20d6f.png)

**Comment by JEAndrew** [comment]
intersectionline.png
![intersectionline](https://cloud.githubusercontent.com/assets/11632667/8911655/7de40390-3453-11e5-99cc-7caabd5ce1c2.png)

**Comment by JEAndrew** [comment]
solidstateline.png
![solidstateline](https://cloud.githubusercontent.com/assets/11632667/8911663/895a7dc6-3453-11e5-842a-c2cb38d5e8b6.png)

**Comment by JEAndrew** [comment]
striation2.png
![striation2](https://cloud.githubusercontent.com/assets/11632667/8911673/941954c6-3453-11e5-839b-0fa05f19c17a.png)

**Comment by JEAndrew** [comment]
vectorline.png
![vectorline](https://cloud.githubusercontent.com/assets/11632667/8911685/a05f2c4c-3453-11e5-9949-87310b744687.png)

**Comment by jessica-azgs** [comment]
@JEAndrew Updated symbols in commit https://github.com/StraboSpot/strabo-mobile/commit/a406829102d55322e9540c442c02e321d6bc8191. See reference issues above for related issues still to be addressed which you mentioned in this thread.
